### ISSUE TITLE
 AssertionError: expected [ 'Buy some cerealBuy some cookies' ] to deeply equal [ Array(3) ]

### ISSUE THREAD

**Issue by wahiche-architech** [jan-molak/serenity-js#118]
Hello.

I am very new to testing and followed your examples word for word, but for some reason I continue to get this error.

I am not sure where it is coming from but here is the stack trace

`Scenario: Adding an item to a list with other items - features\add_new_items.feature:7
   Step: Then his todo list should contain Buy some cookies, Walk the dog, Buy some cereal - features\add_new_items.feature:11
   Step Definition: features\step_definitions\todo_user.steps.ts:29
   Message:
     AssertionError: expected [ 'Buy some cerealBuy some cookies' ] to deeply equal [ Array(3) ]
         at Assertion.assertEqual (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\chai\lib\chai\core\assertions.js:951:19)
         at Assertion.methodWrapper (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\chai\lib\chai\utils\addMethod.js:57:25)
         at getBasePromise.then.then.newArgs (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\chai-as-promised\lib\chai-as-promised.js:297:22)
         at ManagedPromise.invokeCallback_ (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\selenium-webdriver\lib\promise.js:1366:14)
         at TaskQueue.execute_ (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (C:\DEV\tutorial-from-scripts-to-serenity\node_modules\selenium-webdriver\lib\promise.js:2813:27)
         at C:\DEV\tutorial-from-scripts-to-serenity\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by wahiche-architech** [comment]
So I have figured out why this was happening and it is just a user error.  In the todo_user.steps.ts code I was missing a simple thing, I did not return the result.

`this.Given(/^.*that (.*) has a todo list containing (.*)$/, function(actorName: string, items: string) {
        actor = Actor.named(actorName).whoCan(BrowseTheWeb.using(protractor.browser));

        **return** actor.attemptsTo(
            Start.withATodoListContaining(listOf(items))
        );
    });`

**Comment by jan-molak** [comment]
No worries, glad you figured it out!

Another thing I do when I only have one actor and to remember to `return` is to instantiate the actor outside of the step definition:

```typescript
const actor = Actor.named(actorName).whoCan(BrowseTheWeb.using(protractor.browser));
```

And then use the "[fat arrow](https://basarat.gitbooks.io/typescript/content/docs/arrow-functions.html)" notation:

```typescript
this.Given(/^.*that (.*) has a todo list containing (.*)$/, (items: string) => actor.attemptsTo(
    Start.withATodoListContaining(listOf(items))
));
```

Hope that helps!

Jan

**Comment by wahiche-architech** [comment]
Thanks Jan.
