### ISSUE TITLE
E/runner - Unable to start a WebDriver session.

### ISSUE THREAD

**Issue by gizdolok** [jan-molak/serenity-js#139]
Following the steps from the tutorial: 

$> git clone https://github.com/serenity-js/tutorial-from-scripts-to-serenity
$> cd tutorial-from-scripts-to-serenity
$> npm install
$> npm test

I'm getting the following error, while the browser just starts and closes:

> 

[17:24:07] I/local - Selenium standalone server started at http://10.10.4.34:62468/wd/hub
[17:24:09] E/runner - Unable to start a WebDriver session.
[17:24:10] E/launcher - Error: WebDriverError: no such session
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'administrators-iMac-3.local', ip: '10.10.4.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=63.0.3239.108)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.1 x86_64), platform=ANY}]
Session ID: 91c389a3c848faba00d56b80453b8378
    at WebDriverError (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(110000)
    at thenableWebDriverProxy.schedule (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Timeouts._scheduleCommand (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/webdriver.js:1500:25)
    at Timeouts.setScriptTimeout (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/webdriver.js:1483:17)
    at browser_.ready.browser_.ready.then.then (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/runner.ts:281:49)
    at ManagedPromise.invokeCallback_ (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/user/Projects/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[17:24:10] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details. 

>

**Comment by jan-molak** [comment]
Hi there,

This issue doesn't seem related to Serenity/JS, but more likely to Protractor or Selenium.
What if you tried to run an older version of Selenium?

Could you try changing [this line in your `package.json`](https://github.com/serenity-js/tutorial-from-scripts-to-serenity/blob/c1c8e5b5a21d48aee0694f221f9c3efe350c63be/package.json#L7) from:

```
"preprotractor": "webdriver-manager update --standalone --versions.standalone 3.0.1",
```
to:
```
"preprotractor": "webdriver-manager update --standalone --versions.standalone 2.53.1",
```

Let me know if that helps!

Jan

**Comment by csmarcolino** [comment]
Hi Jan-molak, 
I have the exactly same problem as gizdolok. I tried change the version to 2.53.1 as you suggest, but i still got the same error

**Comment by marktigno** [comment]
I was able to run Serenity/JS with the current version of selenium standalone server v3.8.1. Try to update the browser specific drivers (chromedriver for best run) to the latest version. I hope it fix your problem. :)

**Comment by jan-molak** [comment]
Great stuff, I'm glad that you managed to resolve the issue! Thanks for letting us know :-)

**Comment by jan-molak** [comment]
Thanks for sharing, @dpkano!

**Comment by rakeshnambiar** [comment]
@dpkano I tried both the options you suggested but it didn't work in the latest version.

Hi, @gizdolok may I ask you In which file you have commented? In my case also it's listening to 'geckodriver     INFO    Listening on 127.0.0.1:14943' IP and port.

**Comment by rakeshnambiar** [comment]
Hi all, It's resolved. I used the latest released version almost for everything :) Thanks
