### ISSUE TITLE
Cannot read property 'browser' of undefined     at Object.run

### ISSUE THREAD

**Issue by munna73** [jan-molak/serenity-js#140]
I am trying to run a simple test to generate seenity report. I get error below

```
Km-MacBook-Air:confkm$ protractor confs.js
(node:7081) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:04:22] I/launcher - Running 1 instances of WebDriver
[16:04:22] I/local - Starting selenium standalone server...
[16:04:23] I/local - Selenium standalone server started at http://192.168.2.76:58833/wd/hub
[16:04:26] E/launcher - Error: TypeError: Cannot read property 'browser' of undefined
    at Object.run (/Users/km/Documents/Protractor/ProtractorPageObjects/node_modules/serenity-js/src/serenity-protractor/framework/serenity_protractor_framework.ts:21:73)
    at q.then.then.then.then (/usr/local/lib/node_modules/protractor/built/runner.js:405:43)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[16:04:26] E/launcher - Process exited with error code 100
Km-MacBook-Air:confkm$ 
```

`confs.js:`
```
var utils = require('../util/utilities.js');

exports.config = {

	
		
		//directConnect: true,
  
		// Capabilities to be passed to the webdriver instance.
	multiCapabilities: [{
		browserName: 'chrome'
	},
	],

	
		framework: 'custom',
  		frameworkPath: require.resolve('serenity-js'), 
 	seleniumAddress: 'http://localhost:4444/wd/hub',
  
	    specs: [ '../features/*.feature' ],
	    
    cucumberOpts: {
        require:    [ 'features/**/*.js' ],
        format:     'pretty'
    }
}
```

`package.json`:
```
{
	"name": "ProtractorPageObjects",
	"version": "0.0.0",
	"description": "ProtractorPageObjects",
	"main": "app.js",
	"author": {
		"name": "Raman",
		"email": ""
	},
	"devDependencies": {
		"chai": "^4.1.2",
		"cucumber": "^3.2.1",
		"fs-extra": "^5.0.0",
		"jasmine-allure-reporter": "~0.2.3",
		"jasmine-reporters": "~2.0.0",
		"protractor": "^2.2.0",
		"protractor-html-screenshot-reporter": "~0.0.21",
		"protractor-jasmine2-html-reporter": "~0.0.5",
		"protractor-jasmine2-screenshot-reporter": "~0.1.7",
		"selenium-webdriver": "^2.47.1",
		"serenity-cli": "^0.7.1",
		"winston": "~1.0.1"
	},
	"dependencies": {
		"chai-smoothie": "^0.3.2",
		"path": "^0.12.7",
		"promise": "^7.0.4",
		"protractor-cucumber-framework": "^4.1.1",
		"serenity-js": "^1.10.1"
	}
}
```

**Comment by jan-molak** [comment]
Hi there, @karimmd73!

I've [formatted the code samples](https://guides.github.com/features/mastering-markdown/) you have provided and noticed that in your `package.json` you require `protractor-cucumber-framework` instead of [`protractor`](https://www.npmjs.com/package/protractor).

Replace  that with:
```
"protractor": "5.1.2",
```
and you should be good to go!

Please let me know if that helps,
Jan

**Comment by karimmd73** [comment]
In dev dependencies you want me to remove "protractor": "^2.2.0", and replace that with protractor-cucumber-framework. you're statement is  confusing. Can you please clarify.

**Comment by jan-molak** [comment]
Right, sorry if I confused you.

Dev dependencies you need (as per [the website](http://serenity-js.org/overview/installation.html#installation)):
```
"chai": "^4.1.2",
"chai-smoothie": "^0.3.2",
"cucumber": "1.x",
"fs-extra": "^5.0.0",
"protractor": "5.1.2",             // note that the version here is >= 5.x
"serenity-js": "^1.10.1",
"serenity-cli": "^0.7.1",
```

Dependencies you don't need, but currently have:
```
"jasmine-allure-reporter": "~0.2.3",
"jasmine-reporters": "~2.0.0",
"protractor-cucumber-framework": "^4.1.1",
"protractor-html-screenshot-reporter": "~0.0.21",
"protractor-jasmine2-html-reporter": "~0.0.5",
"protractor-jasmine2-screenshot-reporter": "~0.1.7",
```

**Comment by karimmd73** [comment]
Can we use most recent version of cucumber with serenity-js or do we need to stay with older version of cucumber.

**Comment by jan-molak** [comment]
I'm working on enabling support for newer versions of cucumber, so that should be available soon.
Regarding protractor - versions 5.x should work fine, but I haven't tested with the latest version yet.

If you have then I'd love to hear about your experience!
