### ISSUE TITLE
Execution is  break down when I run multiple times the test suite

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#145]
Hi everyone,

I was getting an error when I executed my test suite. The error was:

```
[16:15:13] E/launcher **- Error: WebDriverError: java.net.ConnectException: Connection refused: conne**ct
   at WebDriverError ( ******\node_modules\selenium-webdriver\lib\error.js:27:5)
 
[16:15:13] E/launcher - Process exited with error code 100
```

This was happen because in the step annotation the name of the variable wasn't match with the name in the constructor. For example:

```
@step('{0} enters id **"#id"'**)
```

the variable expected is id, but in the constructor we have something different,

```
constructor(private **otherStuff: number**) {
}
```

The error was not clear and it took a lot of time to find the reason of the failure. Can we implement a meaning message for this error.

Thanks.

Node: 6.11
Serenity JS: 1.10.2

**Comment by jan-molak** [comment]
Hi @jdmesalosada and thanks for reporting this! I'll have a look.

J

**Comment by jan-molak** [comment]
Hey Julian,

I'm looking into this now, but am unable to reproduce the issue you're seeing.

I've tried with adding the following test case to [`step_annotation.spec.ts`](https://github.com/jan-molak/serenity-js/blob/3774960fea94dbd24d545ba4c7424459660f856f/packages/core/spec/recording/step_annotation.spec.ts), but the behaviour looks correct:

```typescript
it(`tries to reproduce the problem`, () => {

    class ATaskWithATypo implements Task {
        private login: string = 'joe-bloggs';

        @step('{0} logs in as #logn')
        performAs(actor: PerformsTasks): PromiseLike<void> {
            return actor.attemptsTo(/* perform some tasks */);
        }
    }

    const task = new ATaskWithATypo();

    return expect(bruce.attemptsTo(task)).to.be.fulfilled.then(() => {

        expect(task.toString()).to.equal('{0} logs in as #logn');
    });

});
```

Would you be able to propose a test case that reproduces the problem?

Thanks!
Jan

**Comment by jdmesalosada** [comment]
Hi Jan, of course, I will create an example, I'll let you know when is ready.

**Comment by jan-molak** [comment]
Great stuff, thanks for your help!

**Comment by jdmesalosada** [comment]
hi Jan you right, I was unable to reproduce this in my machine, I started a project from scratch but is not happening.
The error is intermittent and this is happening in a developer's machine. Something that we saw in his machine was that the chromedriver process is not being finished:

I Keep investigating

![image](https://user-images.githubusercontent.com/5983195/35157532-424f4bda-fd02-11e7-812a-d3dc3bb47e35.png)

**Comment by jan-molak** [comment]
Thanks for the update, Julian! I'm looking forward to hearing more about your findings.

**Comment by jdmesalosada** [comment]
Hi Jan, finally I was able to reproduce the bug in my machine. The full log is the following:

8 scenarios (4 failed, 4 passed)
125 steps (87 skipped, 38 passed)
2m33.891s
Cucumber test run has failed.
[12:23:48] E/launcher - Error: **WebDriverError: java.net.ConnectException: Connection refused: connect**
    at Object.checkLegacyResponse (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\selenium-webdriver\lib\http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.takeScreenshot()
    at thenableWebDriverProxy.schedule (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at thenableWebDriverProxy.takeScreenshot (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\selenium-webdriver\lib\webdriver.js:1092:17)
    at run (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\protractor\lib\browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as takeScreenshot] (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\protractor\lib\browser.ts:74:12)
    at D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\serenity-js\src\serenity-protractor\screenplay\abilities\browse_the_web.ts:42:41
    at D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\@serenity-js\core\src\recording\async.ts:4:8
    at new Promise (<anonymous>)
    at Object.defer (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\@serenity-js\core\src\recording\async.ts:3:12)
    at BrowseTheWeb.takeScreenshot (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\serenity-js\src\serenity-protractor\screenplay\abilities\browse_the_web.ts:42:16)
    **at Photographer.photographWorkOf** (D:\Julian\Projects\zero_account_frontend\zero-account-frontend\node_modules\serenity-js\src\serenity-protractor\stage\photographer.ts:136:36)
[12:23:48] E/launcher - Process exited with error code 100

These are the versions of the tools:

Versión de Java -> 1.8.0_144
Versión de Node -> 8.9.4
Versión del Chromedriver -> Chromedriver 2.35
Versión del Selenium-Server Standalone -> selenium-server-standalone-3.8.1.jar
Versión de Chrome -> 64.0.3282.140

I was reading a little about this error and I found this:

https://github.com/angular/protractor/issues/4451

I'm not sure if this error is related with this.

Should I downgrade the selenium-server-standalone version?

I noticed also that when the execution finished the chromedriver proccess never closes. If you run several times you will have a couple of process running.

I used the command: tasklist | find /I /C "chromedriver" to count the number of proccess running.

**Comment by nbarrett** [comment]
I've seen quite a few conditions like this on my projects where `Photographer` throws exceptions and I'm coming round to thinking that any `WebDriver` type error should probably be swallowed (e.g. take the approach in #148 a step further), as I don't think that the stage crew should ever be responsible for making the screenplay a failure?

**Comment by jdmesalosada** [comment]
My solution for this was made a downgrade for the selenium standalone to 3.0.1.
 In order to make sure all the teams download that specific version I created the following script in the package json:

"webdriver:update": "npm run webdriver-manager update -- --standalone --versions.standalone 3.0.1",
