### ISSUE TITLE
Retrofitting cucumber-protractor-framework

### ISSUE THREAD

**Issue by bali182** [jan-molak/serenity-js#163]
I have followed the guide found on http://serenity-js.org/overview/retrofitting.html to port an existing configuration to use selenium.

I had the following `package.json` (just the relevant parts):
```js
{
  "scripts": {
    "pree2e": "webdriver-manager update --standalone --versions.standalone 3.0.1",
    "e2e": "protractor ./protractor.conf.js"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "cucumber": "^3.2.1",
    "glob": "^7.1.2",
    "protractor": "^5.2.2",
    "protractor-cucumber-framework": "^4.1.1",
  }
}
```

And a protractor config like this:
```js
const glob = require('glob')

const protractor = require.resolve('protractor')
const nodeModules = protractor.substring(0, protractor.lastIndexOf('node_modules') + 'node_modules'.length)
const seleniumJar = glob.sync(`${nodeModules}/protractor/**/selenium-server-standalone-*.jar`).pop()

exports.config = {
  baseUrl: 'http://localhost:3000',
  seleniumServerJar: seleniumJar,
  allScriptsTimeout: 110000,
  disableChecks: true,
  ignoreUncaughtExceptions: true,
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  specs: [
    'features/**/*.feature',
  ],
  cucumberOpts: {
    require: ['features/**/*.steps.js'],
    format: 'summary',
    compiler: 'js:babel-register',
  },
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        'disable-infobars',
        'incognito',
      ],
    },
  },
  onPrepare() {
    browser.waitForAngularEnabled(false)
  },
}
```

I followed the instructions and installed the `serenity-js` module and replaced `require.resolve('protractor-cucumber-framework')` with `require.resolve('serenity-js')`.

Now when I run `npm run e2e` (see in `package.json`, just runs protractor), I get a very generic error with code `100` without any clue where the error is happening: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'e2e' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle wide-demo@0.0.0~pree2e: wide-demo@0.0.0
6 verbose lifecycle wide-demo@0.0.0~pree2e: unsafe-perm in lifecycle true
7 verbose lifecycle wide-demo@0.0.0~pree2e: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/balazs.edes/code/studio-prototype-bitbucket/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin:/Applications/apache/ant/1.9.3/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin:/Applications/apache/ant/1.9.3/bin
8 verbose lifecycle wide-demo@0.0.0~pree2e: CWD: /Users/balazs.edes/code/studio-prototype-bitbucket
9 silly lifecycle wide-demo@0.0.0~pree2e: Args: [ '-c',
9 silly lifecycle   'webdriver-manager update --standalone --versions.standalone 3.0.1' ]
10 silly lifecycle wide-demo@0.0.0~pree2e: Returned: code: 0  signal: null
11 info lifecycle wide-demo@0.0.0~e2e: wide-demo@0.0.0
12 verbose lifecycle wide-demo@0.0.0~e2e: unsafe-perm in lifecycle true
13 verbose lifecycle wide-demo@0.0.0~e2e: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/balazs.edes/code/studio-prototype-bitbucket/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin:/Applications/apache/ant/1.9.3/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin:/Applications/apache/ant/1.9.3/bin
14 verbose lifecycle wide-demo@0.0.0~e2e: CWD: /Users/balazs.edes/code/studio-prototype-bitbucket
15 silly lifecycle wide-demo@0.0.0~e2e: Args: [ '-c', 'protractor ./protractor.conf.js' ]
16 silly lifecycle wide-demo@0.0.0~e2e: Returned: code: 100  signal: null
17 info lifecycle wide-demo@0.0.0~e2e: Failed to exec e2e script
18 verbose stack Error: wide-demo@0.0.0 e2e: `protractor ./protractor.conf.js`
18 verbose stack Exit status 100
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:925:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid wide-demo@0.0.0
20 verbose cwd /Users/balazs.edes/code/studio-prototype-bitbucket
21 verbose Darwin 15.6.0
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
23 verbose node v8.9.1
24 verbose npm  v5.5.1
25 error code ELIFECYCLE
26 error errno 100
27 error wide-demo@0.0.0 e2e: `protractor ./protractor.conf.js`
27 error Exit status 100
28 error Failed at the wide-demo@0.0.0 e2e script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 100, true ]
```

Can you advise, what this might be or how to debug further?

**Comment by jan-molak** [comment]
Hi there, 

Looks like you might be using Cucumber 3 while Serenity/JS supports Cucumber 1.3.
Support for newer versions is in the pipeline, though! (#28)

Jan

**Comment by maddymathavan** [comment]
Hi I am using protractor with cucumber and serneity when i am running e2e i m getting below error.
webpack: Compiled with warnings.
[19:00:02] E/downloader - undefined
[19:00:02] I/update - chromedriver: file exists C:\Users\kmathav\OCP_UI\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.46.zip
[19:00:02] I/update - chromedriver: unzipping chromedriver_2.46.zip
[19:00:02] I/update - chromedriver: chromedriver_2.46.exe up to date
[19:00:02] I/launcher - Running 1 instances of WebDriver
[19:00:02] I/direct - Using ChromeDriver directly...
[19:00:02] E/downloader - undefined

DevTools listening on ws://127.0.0.1:55085/devtools/browser/1b0ad00b-6f04-4590-88b3-3a58fe520ba6
start
Cannot read property 'set' of undefined
[19:00:36] I/launcher - 0 instance(s) of WebDriver still running
[19:00:36] I/launcher - chrome #01 failed 1 test(s)
[19:00:36] I/launcher - overall: 1 failed spec(s)
[19:00:36] E/launcher - Process exited with error code 1
