### ISSUE TITLE
Timeout after logging into Angular App

### ISSUE THREAD

**Issue by abdul-farhat** [jan-molak/serenity-js#172]
Hi,

The SUT runs Angular v1.6.4. 

Once I log in to my app (which works with serenity-js) my commands timeout i.e. elements can't be found.

I run similar commands with protractor-cucumber-typescript framework and they work fine post login.

Thoughts??

Example:

```
import { PerformsTasks, Task } from 'serenity-js/lib/screenplay';
import { Open, Click, Enter, Wait, Is } from 'serenity-js/lib/screenplay-protractor';

import { protractor } from 'protractor';

import { Login  } from '../components/login';
import { QuickWorkspaceMenu  } from '../components/quick_workspace_menu';


export class LoginToSUT implements Task {

    static with(username: string, password: string) {                     
        return new LoginToSUT(username, password);
    }

    performAs(actor: PerformsTasks): PromiseLike<void> {   
        return actor.attemptsTo(
            Open.browserOn('/QA29v36'),                            
            Enter.theValue(this.username)
                .into(Login.Username)
                .thenHit(protractor.Key.TAB),
            Enter.theValue(this.password)
                .into(Login.Password),
            Click.on(Login.Button),                                                                                      //PRE LOGIN
            Wait.until(QuickWorkspaceMenu.ManageQuickWorkspaceIcon, Is.clickable()) //POST LOGIN STEP
        );
    }
    
    constructor(private username: string, private password: string) {                
    }                                                   
}
```
Console:
```
PS C:\Users\farhata\github\tutorial-from-scripts-to-serenity> npm test

> tutorial-from-scripts-to-serenity@1.0.0 pretest C:\Users\farhata\github\tutorial-from-scripts-to-serenity
> serenity update

info: Serenity BDD CLI jar file is up to date :-)

> tutorial-from-scripts-to-serenity@1.0.0 test C:\Users\farhata\github\tutorial-from-scripts-to-serenity
> failsafe clean protractor

[clean]
[clean] > tutorial-from-scripts-to-serenity@1.0.0 clean C:\Users\farhata\github\tutorial-from-scripts-to-serenity
[clean] > rimraf target
[clean]
[failsafe] Script 'clean' exited with code 0
[protractor]
[protractor] > tutorial-from-scripts-to-serenity@1.0.0 protractor C:\Users\farhata\github\tutorial-from-scripts-to-serenity
[protractor] > protractor ./protractor.conf.js --verbose
[protractor]
[protractor] (node:22204) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[protractor] [12:07:35] I/launcher - Running 1 instances of WebDriver
[protractor] [12:07:35] I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
[protractor] Feature: Search for an existing Site within Kalibrate
[protractor]
[protractor]    As a Pricing Analyst I would like to be able to search for any Site using the Search Widget
[protractor]
[protractor]   Scenario: Search for a site using the Search Widget
[protractor] 12:07:41.535 | SceneTagged: [object Promise]
[protractor] 12:07:41.536 | SceneTagged: [object Promise]
[protractor] 12:07:41.534 | SceneStarts: Search for a site using the Search Widget (category: Search for an existing Site within Kalibrate, path: C:\Users\farhata\github\tutorial-from-scripts-to-serenity\features\search_for_site.feature:5, id: Search for an existing Site within Kalibrate:5:Search for a site using the Search Widget)
[protractor] 12:07:41.541 | ActivityStarts: Given that the Pricing Analyst has logged in
[protractor] 12:07:41.554 | ActivityStarts: Pricing Analyst opens the browser at "/QA29v36"
[protractor] 12:07:48.253 | ActivityFinished: Pricing Analyst opens the browser at "/QA29v36" (result: SUCCESS)
[protractor] 12:07:48.258 | ActivityStarts: Pricing Analyst enters AFarhat into the "Username" input box
[protractor] 12:07:49.086 | ActivityFinished: Pricing Analyst enters AFarhat into the "Username" input box (result: SUCCESS)
[protractor] 12:07:49.087 | ActivityStarts: Pricing Analyst hits the TAB key
[protractor] 12:07:49.184 | ActivityFinished: Pricing Analyst hits the TAB key (result: SUCCESS)
[protractor] 12:07:49.186 | ActivityStarts: Pricing Analyst enters letmein123 into the "Password" input box
[protractor] 12:07:49.345 | ActivityFinished: Pricing Analyst enters letmein123 into the "Password" input box (result: SUCCESS)
[protractor] 12:07:49.345 | ActivityStarts: Pricing Analyst clicks on the "Login" button
[protractor] 12:07:49.441 | ActivityFinished: Pricing Analyst clicks on the "Login" button (result: SUCCESS)
[protractor]   × Given that the Pricing Analyst has logged in
[protractor] 12:08:11.545 | ActivityFinished: Given that the Pricing Analyst has logged in (result: ERROR, error:Error: function timed out after 30000 milliseconds)
[protractor] 12:08:11.545 | ActivityStarts: Then should see DEFAULT
[protractor]   - Then should see DEFAULT
[protractor] 12:08:11.546 | ActivityFinished: Then should see DEFAULT (result: SKIPPED)
[protractor] 12:08:41.549 | SceneFinished: Search for a site using the Search Widget (category: Search for an existing Site within Kalibrate, path: C:\Users\farhata\github\tutorial-from-scripts-to-serenity\features\search_for_site.feature:5, id: Search for an existing Site within Kalibrate:5:Search for a site using the Search Widget) (result: ERROR, error:Error: function timed out after 30000 milliseconds)
[protractor]
[protractor] Failures:
[protractor]
[protractor] 1) Scenario: Search for a site using the Search Widget - features\search_for_site.feature:5
[protractor]    Step: Given that the Pricing Analyst has logged in - features\search_for_site.feature:7
[protractor]    Step Definition: node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:47
[protractor]    Message:
[protractor]      function timed out after 30000 milliseconds
[protractor]
[protractor] 2) Scenario: Search for a site using the Search Widget - features\search_for_site.feature:5
[protractor]    Step: After
[protractor]    Step Definition: features\step_definitions\hooks.ts:5
[protractor]    Message:
[protractor]      function timed out after 30000 milliseconds
[protractor]
[protractor] 1 scenario (1 failed)
[protractor] 2 steps (1 failed, 1 skipped)
[protractor] 1m00.004s
[protractor] Cucumber test run has failed.
[protractor] [12:09:07] I/launcher - 0 instance(s) of WebDriver still running
[protractor] [12:09:07] I/launcher - chrome #01 failed 2 test(s)
[protractor] [12:09:07] I/launcher - overall: 2 failed spec(s)
[protractor] [12:09:07] E/launcher - Process exited with error code 1
[protractor] npm ERR! code ELIFECYCLE
[protractor] npm ERR! errno 1
[protractor] npm ERR! tutorial-from-scripts-to-serenity@1.0.0 protractor: `protractor ./protractor.conf.js --verbose`
[protractor] npm ERR! Exit status 1
[protractor] npm ERR!
[protractor] npm ERR! Failed at the tutorial-from-scripts-to-serenity@1.0.0 protractor script.
[protractor] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[protractor]
[protractor] npm ERR! A complete log of this run can be found in:
[protractor] npm ERR!     C:\Users\farhata\AppData\Roaming\npm-cache\_logs\2018-02-22T12_09_07_221Z-debug.log
[failsafe] Script 'protractor' exited with code 1
npm ERR! Test failed.  See above for more details.
```
Keeping getting hammered with this in webdriver server:

```
12:07:49.363 INFO - To downstream: {"sessionId":"a833aa0f235f2e005f0278b381f2379d","status":0,"value":null}
12:07:49.368 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:07:49.369 INFO - Handler thread for session a833aa0f235f2e005f0278b381f2379d (chrome): Executing POST on /session/a833aa0f235f2e005f0278b381f2379d/execute (handler: ServicedSession)
12:07:49.370 INFO - To upstream: {"script":"try { return (function (searchText, using) {\n  using = using || document;\n\n  var elements = using.querySelectorAll('button, input[type=\"button\"], input[type=\"submit\"]');\n  var matches = [];\n  for (var i = 0; i < elements.length; ++i) {\n    var element = elements[i];\n    var elementText;\n    if (element.tagName.toLowerCase() == 'button') {\n      elementText = element.textContent || element.innerText || '';\n    } else {\n      elementText = element.value;\n    }\n    if (elementText.trim() === searchText) {\n      matches.push(element);\n    }\n  }\n\n  return matches;\n}).apply(this, arguments); }\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }","args":["Login",null,"body"]}
12:07:49.378 INFO - To downstream: {"sessionId":"a833aa0f235f2e005f0278b381f2379d","status":0,"value":[{"ELEMENT":"0.3427034880654263-3"}]}
12:07:49.382 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:07:49.383 INFO - Handler thread for session a833aa0f235f2e005f0278b381f2379d (chrome): Executing POST on /session/a833aa0f235f2e005f0278b381f2379d/element/0.3427034880654263-3/click (handler: ServicedSession)
12:07:49.384 INFO - To upstream: {}
12:07:49.438 INFO - To downstream: {"sessionId":"a833aa0f235f2e005f0278b381f2379d","status":0,"value":null}
12:07:49.452 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:07:49.453 INFO - Handler thread for session a833aa0f235f2e005f0278b381f2379d (chrome): Executing POST on /session/a833aa0f235f2e005f0278b381f2379d/execute_async (handler: ServicedSession)
12:07:49.456 INFO - To upstream: {"script":"try { return (function anonymous() {\nfunction getNg1Hooks(selector, injectorPlease) {\n  function tryEl(el) {\n    try {\n      if (!injectorPlease && angular.getTestability) {\n        var $$testability = angular.getTestability(el);\n        if ($$testability) {\n          return {$$testability: $$testability};\n        }\n      } else {\n        var $injector = angular.element(el).injector();\n        if ($injector) {\n
    return {$injector: $injector};\n        }\n      }\n    } catch(err) {} \n  }\n  function trySelector(selector) {\n    var els = document.querySelectorAll(selector);\n    for (var i = 0; i < els.length; i++) {\n      var elHooks = tryEl(els[i]);\n      if (elHooks) {\n        return elHooks;\n      }\n    }\n  }\n\n  if (selector) {\n    return trySelector(selector);\n  } else if (window.__TESTABILITY__NG1_APP_ROOT_INJECTOR__) {\n    var $injector = window.__TESTABILITY__NG1_APP_ROOT_INJECTOR__;\n    var $$testability = null;\n    try {\n      $$testability = $injector.get('$$testability');\n    } catch (e) {}\n    return {$injector: $injector, $$testability: $$testability};\n  } else {\n    return tryEl(document.body) ||\n        trySelector('[ng-app]') || trySelector('[ng\\\\:app]') ||\n        trySelector('[ng-controller]') || trySelector('[ng\\\\:controller]');\n  }\n};  return (function (rootSelector, callback) {\n  try {\n    if (window.angular && !(window.angular.version &&\n          window.angular.version.major > 1)) {\n      /* ng1 */\n      var hooks = getNg1Hooks(rootSelector);\n      if (hooks.$$testability) {\n        hooks.$$testability.whenStable(callback);\n      } else if (hooks.$injector) {\n        hooks.$injector.get('$browser').\n            notifyWhenNoOutstandingRequests(callback);\n      } else if (!!rootSelector) {\n        throw new Error('Could not automatically find injector on page: \"' +\n            window.location.toString() + '\".  Consider using config.rootEl');\n      } else {\n        throw new Error('root element (' + rootSelector + ') has no injector.' +\n           ' this may mean it is not inside ng-app.');\n      }\n    } else if (rootSelector && window.getAngularTestability) {\n      var el = document.querySelector(rootSelector);\n      window.getAngularTestability(el).whenStable(callback);\n    } else if (window.getAllAngularTestabilities) {\n      var testabilities = window.getAllAngularTestabilities();\n      var count = testabilities.length;\n      var decrement = function() {\n        count--;\n        if (count === 0) {\n          callback();\n        }\n      };\n      testabilities.forEach(function(testability) {\n        testability.whenStable(decrement);\n      });\n    } else if (!window.angular) {\n      throw new Error('window.angular is undefined.  This could be either ' +\n
      'because this is a non-angular page or because your test involves ' +\n          'client-side navigation, which can interfere with Protractor\\'s ' +\n          'bootstrapping.  See http://git.io/v4gXM for details');\n    } else if (window.angular.version >= 2) {\n      throw new Error('You appear to be using angular, but window.' +\n          'getAngularTestability was never set.  This may be due to bad ' +\n          'obfuscation.');\n    } else {\n      throw new Error('Cannot get testability API for unknown angular ' +\n          'version \"' + window.angular.version + '\"');\n    }\n  } catch (err) {\n    callback(err.message);\n  }\n}).apply(this, arguments);\n}).apply(this, arguments); }\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }","args":["body"]}
12:08:11.549 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:08:11.550 INFO - Handler thread for session a833aa0f235f2e005f0278b381f2379d (chrome): Executing POST on /session/a833aa0f235f2e005f0278b381f2379d/execute (handler: ServicedSession)
12:08:11.553 INFO - To upstream: {"script":"window.sessionStorage.clear();\nwindow.localStorage.clear();","args":[]}
12:08:41.563 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:08:41.566 INFO - Handler thread for session a833aa0f235f2e005f0278b381f2379d (chrome): Executing DELETE on /session/a833aa0f235f2e005f0278b381f2379d (handler: ServicedSession)
12:09:07.042 INFO - To downstream: {"sessionId":"a833aa0f235f2e005f0278b381f2379d","status":0,"value":null}
12:09:07.047 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:09:07.048 INFO - Handler thread for session a833aa0f235f2e005f0278b381f2379d (chrome): Executing POST on /session/a833aa0f235f2e005f0278b381f2379d/elements (handler: ServicedSession)
12:09:07.050 INFO - To upstream: {"using":"css selector","value":"div[class^='menu-block workspace'] > span"}
12:09:07.050 INFO - To downstream: {"sessionId":"a833aa0f235f2e005f0278b381f2379d","status":0,"value":null}
12:09:07.186 INFO - To downstream: {"sessionId":"a833aa0f235f2e005f0278b381f2379d","status":0,"value":null}
12:09:07.189 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@cd1bc13
12:09:07.225 INFO - To downstream: {"sessionId":"","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.16299 x86_64)"}}
12:09:07.225 INFO - To downstream: {"sessionId":"","status":0,"value":null}
2018-02-22 12:09:07.230:WARN:osjs.HttpChannel:qtp1712536284-14: /wd/hub/session/a833aa0f235f2e005f0278b381f2379d/elements
java.lang.IllegalStateException: Committed
        at org.seleniumhq.jetty9.server.HttpChannel.resetBuffer(HttpChannel.java:841)
        at org.seleniumhq.jetty9.server.HttpOutput.resetBuffer(HttpOutput.java:928)
        at org.seleniumhq.jetty9.server.Response.resetBuffer(Response.java:1312)
        at org.seleniumhq.jetty9.server.Response.resetForForward(Response.java:1305)
        at org.seleniumhq.jetty9.server.Response.reset(Response.java:1244)
        at org.seleniumhq.jetty9.server.Response.reset(Response.java:1239)
        at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverServlet.java:257)
        at org.openqa.selenium.remote.server.WebDriverServlet.doPost(WebDriverServlet.java:161)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.WebDriverServlet.service(WebDriverServlet.java:121)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by nbarrett** [comment]
Hi @abdul-farhat - I have a couple of suggestions/thoughts that you could experiment to see whether behaviour changes:

1 - is *every* part of your application angular? It might be worth trying this  at a global level
```
  onPrepare: function () {
    browser.ignoreSynchronization = true;
  }
```
or directly before the `Activity` where you are having trouble you could try `UseAngular.disableSynchronisation()`
2 - As you are using chrome, have you tried  `directConnect: true`? That can simplify the webdriver connectivity!
3 - nail your app to a known 'good' selenium version by using this command `"webdriver:update": "npm run webdriver-manager update --gecko false --standalone --versions.standalone=2.53.1 --versions.chrome 2.35`

**Comment by abdul-farhat** [comment]
@nbarett Thanks for that. 

ignoreSynchronization seems to do the trick. 

However, what impact would ignoreSynchronization have on the rest of this framework and how to accommodate? i.e. recording time taken for each cucumber step or the screenshot functionality for the reports would now not work.

**Comment by nbarrett** [comment]
Ah, glad to have been some help. My experience with `ignoreSynchronization:true` is that you can no longer rely on protractor to do the waiting for you, which means that you might have to do more elaborate wait strategies in your Tasks. When the value is set false (default), Protractor will synchronise with your page before performing actions. This means waiting for all $timeout or $http requests to resolve, as well as letting the current $digest cycle finish. 

However it doesn't have to be a global setting, as `UseAngular.disableSynchronisation()`, `UseAngular.enableSynchronisation()` can surround interactions with non-angular pages, or parts that are giving you synchronisation problems? I've done quite a bit of work with serenity-js and a non-angular app and it doesn't affect any of the recording time/screenshot. That works for anything based on your crew settings.

**Comment by abdul-farhat** [comment]
Yeah, thought that would be the case.

Maybe getting a bit off topic...

How would one differentiate between a non-angular page/part against angular? Just thinking about a dynamic solution (probably open up another can of worms)

**Comment by nbarrett** [comment]
Hmmm... well If you are working on the project team that is developing the system(s), you would probably be able to find out with a few dev-type discussions which parts are angular/non angular. If that's not possible and you know that 'most' of it is angular, then keep `ignoreSychronisation:false`, and then automate your way 'into' the application and if a new Task works, great, otherwise add `UseAngular.disableSynchronisation()` before you start that Task and then `UseAngular.enableSynchronisation()` when it's finished?

**Comment by ctaepper** [comment]
we encountered a similar problem and while it helps to `disableSynchronisation()`, it is not the root of the problem. In our case, we are using [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc) for authentication. this library sets up some long running observables which cause the timeout. please have a look at the open [pull request](https://github.com/manfredsteyer/angular-oauth2-oidc/pull/233) in order to find out how to discover long running tasks in your app. I am pretty sure, you are encountering something like that
