### ISSUE TITLE
Running npm run protractor --- silent inside docker container - Error: Error: Timed out waiting for the WebDriver server at

### ISSUE THREAD

**Issue by kdp88** [jan-molak/serenity-js#204]
Running serenity inside docker

```
> app@0.0.0 preserenity /app
> serenity update

[32minfo[39m: Looks like you need the latest Serenity BDD CLI jar. Let me download it for you...
[32minfo[39m: Downloaded to /app/node_modules/serenity-cli/.cache/serenity-cli-1.8.0-all.jar

> app@0.0.0 serenity /app
> npm run arc-merge-languages && npm run protractor --silent
```

Getting this error

```
[18:09:22] I/launcher - Running 1 instances of WebDriver
[18:09:22] I/local - Starting selenium standalone server...
[18:09:22] W/launcher - Ignoring uncaught error Error: spawn java ENOENT
[18:09:52] E/launcher - Error: Error: Timed out waiting for the WebDriver server at http://172.17.0.2:49534/wd/hub
    at onError (/app/node_modules/selenium-webdriver/http/util.js:102:16)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
My `protractor.conf.js` has this inside

```
const
  glob         = require('glob'),
  protractor   = require.resolve('protractor'),
  node_modules = protractor.substring(0, protractor.lastIndexOf('node_modules') + 'node_modules'.length),
  seleniumJar  = glob.sync(`${node_modules}/protractor/**/selenium-server-standalone-*.jar`).pop();

exports.config = {

  // baseUrl: 'https://arc-composite-frontend-main.aws-dev.billtrustinternal.net',
  baseUrl: 'http://localhost:4200',

  // seleniumServerJar: seleniumJar,

  // https://github.com/angular/protractor/blob/master/docs/timeouts.md
  allScriptsTimeout: 110000,

  disableChecks: true,

  // https://github.com/protractor-cucumber-framework/protractor-cucumber-framework#uncaught-exceptions
  ignoreUncaughtExceptions: true,

  framework: 'custom',
  frameworkPath: require.resolve('serenity-js'),

  specs: [ 'e2e/features/**/*.feature' ],

  cucumberOpts: {
    require:    [ 'e2e/features/**/*.ts' ],
    format:     'pretty',
    compiler:   'ts:ts-node/register'
  },

....
}
```
PLEASE HELP

**Comment by marktigno** [comment]
Another thing, before starting the docker container, you need to add this args on the docker run command:
`docker run --rm -ti -v /dev/shm:/dev/shm --privileged your-docker-image bash`

Also run google chrome `--no-sandbox` mode.

**Comment by kdp88** [comment]
@marktigno thanks for this, before trying your solution i tried adding 
`directConnect: true,`
to the `protractor.conf.js` and that did the trick
