### ISSUE TITLE
ReferenceError: by is not defined - While executes the test individually from IntelliJ IDEA

### ISSUE THREAD

**Issue by rakeshnambiar** [jan-molak/serenity-js#214]
ReferenceError: by is not defined - While executes the test individually from IntelliJ IDEA. Whereas the Test runs properly using 'npm' commands.

ReferenceError: by is not defined
    at new TodoListPage (C:\serenity-js\examples\todomvc-protractor-cucumber-pageobjects\src\todolist.page.js:11:33)
    at Object.<anonymous> (C:\serenity-js\examples\todomvc-protractor-cucumber-pageobjects\src\todolist.page.js:91:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\serenity-js\examples\todomvc-protractor-cucumber-pageobjects\src\manage_the_todo_list\step_definitions\todo_user.steps.js:2:20)

**Comment by jan-molak** [comment]
Hi @rakeshnambiar! It's difficult to suggest anything without seeing your code... Based on the error I'd guess that perhaps you haven't imported `by` from the protractor module?

```typescript
import { by } from 'protractor';
```
