### ISSUE TITLE
Unable to launch tests on IE11 with Mocha

### ISSUE THREAD

**Issue by igorvik** [jan-molak/serenity-js#239]
I tried to run the default SerenityJS (Mocha) project and got the next error for IE:

const
    crew = require('serenity-js/lib/stage_crew');
exports.config = {

    baseUrl: 'http://**[your link]**',
    seleniumAddress: "http://**[your IE driver link]**:4444/wd/hub",
    getPageTimeout: 100000,
    allScriptsTimeout: 110000,
    framework: 'custom',
    frameworkPath: require.resolve('serenity-js'),

    specs: ['spec/**/dashboardSimple0.spec.ts'],

    mochaOpts: {
        format: 'pretty',
        compiler: 'ts:ts-node/register'
    },

    serenity: {
        dialect: 'mocha',
        crew: [
            crew.serenityBDDReporter(),
            crew.consoleReporter(),
            crew.Photographer.who(_ => _
                .takesPhotosOf(_.Failures)
                .takesPhotosWhen(_.Activity_Finishes)
            )
        ]
    },
    multiCapabilities: [{
        browserName: 'internet explorer',

    }]
}; 

/usr/bin/node /home/anyuser/wc/seed-cucumber/node_modules/protractor/bin/protractor /home/anyuser/Downloads/idea-IU-172.4343.14/plugins/JavaScriptLanguage/helpers/protractor-intellij/lib/protractor-intellij-config.js --intellijOriginalConfigFile=/home/anyuser/wc/registry-tests-ui/seed-mocha/protractor.conf.js --disableChecks
(node:7510) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[11:56:46] I/launcher - Running 1 instances of WebDriver
[11:56:46] I/hosted - Using the selenium server at http://**[your IE driver link]**:4444/wd/hub
[11:56:49] E/launcher - Unable to parse new session response: {"value":{"sessionId":"7ec54d22-2874-42f2-a4d5-aae8c04caad0","capabilities":{"acceptInsecureCerts":false,"browserName":"internet explorer","browserVersion":"11","pageLoadStrategy":"normal","platformName":"windows","proxy":{},"se:ieOptions":{"browserAttachTimeout":0,"elementScrollBehavior":0,"enablePersistentHover":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.fileUploadDialogTimeout":3000,"ie.forceCreateProcessApi":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:40538/","nativeEvents":true,"requireWindowFocus":false},"setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"webdriver.remote.sessionid":"7ec54d22-2874-42f2-a4d5-aae8c04caad0"}}}
[11:56:49] E/launcher - WebDriverError: Unable to parse new session response: {"value":{"sessionId":"7ec54d22-2874-42f2-a4d5-aae8c04caad0","capabilities":{"acceptInsecureCerts":false,"browserName":"internet explorer","browserVersion":"11","pageLoadStrategy":"normal","platformName":"windows","proxy":{},"se:ieOptions":{"browserAttachTimeout":0,"elementScrollBehavior":0,"enablePersistentHover":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.fileUploadDialogTimeout":3000,"ie.forceCreateProcessApi":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:40538/","nativeEvents":true,"requireWindowFocus":false},"setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"webdriver.remote.sessionid":"7ec54d22-2874-42f2-a4d5-aae8c04caad0"}}}
    at doSend.then.response (/home/anyuser/wc/seed-cucumber/node_modules/selenium-webdriver/lib/http.js:445:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/anyuser/wc/seed-cucumber/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at createDriver (/home/anyuser/wc/seed-cucumber/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/home/anyuser/wc/seed-cucumber/node_modules/selenium-webdriver/index.js:632:14)
    at Hosted.getNewDriver (/home/anyuser/wc/seed-cucumber/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
    at Runner.createBrowser (/home/anyuser/wc/seed-cucumber/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/anyuser/wc/seed-cucumber/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/anyuser/wc/seed-cucumber/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/anyuser/wc/seed-cucumber/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/anyuser/wc/seed-cucumber/node_modules/q/q.js:796:13)
    at /home/anyuser/wc/seed-cucumber/node_modules/q/q.js:556:49
[11:56:49] E/launcher - Process exited with error code 199

Process finished with exit code 199
Empty test suite.

**Comment by jan-molak** [comment]
It seems like angular/protractor#4445 could be related and potentially provide some answers.

Let me know if that helps?
Jan

**Comment by igorvik** [comment]
Hey, Jan!

Thank you for your response. We downgraded selenium-server-standalone and IEDriver to 3.4.0, and it solved the issue. But it's weird because the issue doesn't appear when to run serenity-cucumber pair on newest versions of server and driver (3.13.0).

Best regards, Ihor

**Comment by jan-molak** [comment]
Glad you got it fixed, thanks for letting me know!
