### ISSUE TITLE
RangeError: Maximum call stack size exceeded - lodash

### ISSUE THREAD

**Issue by fs-transformuk** [jan-molak/serenity-js#324]
Hi,

Getting

After running a couple of steps when the code hits the step below (after the error); specifically any assertion after `TabsContainer.DeputyTasks_Tab` check I get the lodash error shown below.

Error below:
`[10:40:31] E/launcher - Maximum call stack size exceeded
[10:40:31] E/launcher - RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at baseGetTag (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:3078:51)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2663:19)
    at /app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:537:11)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2696:7)
    at cloneSet (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:4591:28)
    at initCloneByTag (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:6254:18)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2680:20)
    at /app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:537:11)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2696:7)
    at /app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:537:11)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2696:7)
    at /app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:537:11)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2696:7)
    at cloneSet (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:4591:28)
    at initCloneByTag (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:6254:18)
    at baseClone (/app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2680:20)
    at /app/node_modules/@serenity-js/core/node_modules/lodash/lodash.js:2702:34
[10:40:31] E/launcher - Process exited with error code 199
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Step definition below:
```this.Then(/^.*the (.*) page is loading as expected$/, function (pageName: string) {
		switch (pageName.toLowerCase()) {
			...
			// deputy hub
			case 'deputy record death':
				return this.stage.theActorInTheSpotlight().attemptsTo(
					See.if(WebElement.of(DeputyRecordDeathForm.Record_Death_Title), el => expect(el).to.eventually.be.displayed),
					See.if(WebElement.of(TabsContainer.DeputyDetails_Tab), el => expect(el).to.eventually.be.displayed),
					See.if(WebElement.of(TabsContainer.Clients_Tab), el => expect(el).to.eventually.be.displayed),
					See.if(WebElement.of(TabsContainer.DeputyTasks_Tab), el => expect(el).to.eventually.be.displayed),
					See.if(WebElement.of(TabsContainer.Warnings_Tab), el => expect(el).to.eventually.be.displayed),
					See.if(WebElement.of(TabsContainer.Timeline_Tab), el => expect(el).to.eventually.be.displayed),
					See.if(WebElement.of(TabsContainer.Documents_Tab), el => expect(el).to.eventually.be.displayed),
					See.if(Attribute.of(BaseForm.Form_Submit_Button).called('disabled'), value => expect(value).to.eventually.equal('true'))
				);
...

			default:
				throw new Error('Unknown page type supplied');
		}
	});```

**Comment by fs-transformuk** [comment]
@jan-molak any ideas?

**Comment by jan-molak** [comment]
Hey @fs-transformuk - it's difficult to tell without seeing the code, especially that the stack trace mentions Lodash rather than Serenity/JS. Would you be able to create a sample project on github demonstrating the issue so that I can try to reproduce it?

**Comment by fs-transformuk** [comment]
@jan-molak thanks for getting back to me. Getting a sample project on the go as there are quite a few complex tasks before it gets to the assertions. Is there a way I can get it to spew out a stack trace?

**Comment by fs-transformuk** [comment]
@jan-molak Hi mate, ok so that error was my mistake; I was looking for an element that wasnt present on the screen (which shouldnt be either), my assertion was wrong. The new question is if an element is present then should I not be seeing a more suitable error?

**Comment by jan-molak** [comment]
Hey @fs-transformuk - so what's the current behaviour and the behaviour you'd rather see instead?

**Comment by fs-transformuk** [comment]
Hey @jan-molak, sorry been trying to get a ticket over the line. Basically, the error I was getting was misleading in that it was pointing towards lodash when I would have expected something along the lines of that element you were asserting on isnt there.

I will create a sample project and then open a new issue to explain in more detail.  I think this issue itself if resolved now.

Thanks
