### ISSUE TITLE
"An illegal reflective access operation has occurred" Error while generating serenity report

### ISSUE THREAD

**Issue by samaysimantbarik** [jan-molak/serenity-js#348]
Hi,

I am using serenity protractor cucumber as a tool stack for my automation project.
I recently upgraded my Java version from 8 to 12 and I get the below error while running serenity report:

**Error: WARNING: An illegal reflective access operation has occurred
    at C:\Projects\UNSW TESTS\e2e\serenity-e2e\node_modules\serenity-cli\lib\actions\logging.js:9:35
    at process._tickCallback (internal/process/next_tick.js:68:7)**

Package versions:
 "protractor": "^5.4.2",
    "protractor-cucumber-framework": "^6.1.3",
    "rimraf": "2.5.4",
    "serenity-cli": "^0.11.3",
    "serenity-js": "^1.10.13"

Script:
"pretest": "serenity update",
 "report": "serenity run"

Note: I was able to generate the report on Java 8.

Kindly help.

**Comment by jan-molak** [comment]
Hi @samaysimantbarik.

Could you please check if you can replace the `serenity-cli`  module with the latest alpha of `@serenity-js/serenity-bdd`? It ships with a newer version of Serenity BDD CLI (the Java reporter), which should be compatible with Java 12.

You'd also need to change the `script` section of your `package.json` to call:
```
"pretest": "serenity-bdd update",
"report": "serenity-bdd run"
```

Let me know if that helps.
Jan

**Comment by samaysimantbarik** [comment]
Hi Jan,

Thanks for your response.

It seems that the new version of CLI is primarily for REST based test cases. I got the below error upon running Pretest.
C:\Projects\UNSW TESTS\e2e\serenity-e2e>npm run pretest


> serenity-bdd update

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@serenity-js/rest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Projects\UNSW TESTS\e2e\serenity-e2e\node_modules\@serenity-js\serenity-bdd\lib\cli\stage\Actors.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

Than after I installed npm i @serenity-js/rest and reran , I got error for not having axios.

> serenity-bdd update

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)

Is there any way to use this latest version just for web apps.

**Comment by jan-molak** [comment]
Hi @samaysimantbarik - the new CLI is for both REST and Web-based test cases.
The reason why it has a dependency on Axios and `@serenity-js/rest` is that it uses them to download the Serenity BDD jar. 
They're specified as `peerDependencies`, so that's why you'd need them in your `package.json`.

Sorry, I should've mentioned that earlier. Hope that clarifies it!

**Comment by jan-molak** [comment]
Raised as serenity-bdd/serenity-cli#6

**Comment by SJ1591** [comment]
While trying this solution, I am getting error:
serenityjs-cucumber-protractor-standalone@1.0.0 pretest-local /Users/sachin.joshi/np-cms-webapp/np-automation
> serenity-bdd update

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@serenity-js/core/lib/model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/sachin.joshi/np-cms-webapp/np-automation/node_modules/@serenity-js/serenity-bdd/lib/cli/model/Complaint.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serenityjs-cucumber-protractor-standalone@1.0.0 pretest-local: `serenity-bdd update`
npm ERR! Exit status 1

@jan-molak I have installed following packages:
   "@serenity-js/assertions": "^2.0.1-alpha.2",
    "@serenity-js/rest": "^1.1.1",
    "@serenity-js/serenity-bdd": "^2.0.1-alpha.77",

**Comment by jan-molak** [comment]
@SJ1591 - please make sure use the same version for all the `@serenity-js/*` packages, since they're always released together. The latest alpha is currently `2.0.1-alpha.115` (you can check that by going to https://www.npmjs.com/package/@serenity-js/core and switching to the "versions" tab)

**Comment by SJ1591** [comment]
> @SJ1591 - please make sure use the same version for all the `@serenity-js/*` packages, since they're always released together. The latest alpha is currently `2.0.1-alpha.115` (you can check that by going to https://www.npmjs.com/package/@serenity-js/core and switching to the "versions" tab)

Thank you.. @jan-molak It is working fine now.
