### ISSUE TITLE
"TypeError: Cannot read property 'println' of undefined" when trying to use new ConsoleReporter()

### ISSUE THREAD

**Issue by testifyqa** [jan-molak/serenity-js#412]
When I try to run npm test with new ConsoleReporter() in my serenity config block, I get the error "Error: TypeError: Cannot read property 'println' of undefined"

If I remove it, I do not.

my conf file looks like below, cheers...

```
const
    { Photographer, TakePhotosOfFailures } = require('@serenity-js/protractor'),
    { SerenityBDDReporter } = require('@serenity-js/serenity-bdd'),
    { ConsoleReporter } = require('@serenity-js/console-reporter');

exports.config = { 
    directConnect: true,
    allScriptsTimeout: 120000,
    capabilities: {
        browserName: 'chrome'
    },
    specs: ['./features/*.feature'],
    framework: 'custom',
    frameworkPath: require.resolve('@serenity-js/protractor/adapter'), 
    onPrepare: () => {
        require('ts-node').register({ 
            project: './tsconfig.json'
        });
    },
    serenity: {
        runner: 'cucumber',
        crew: [
            Photographer.whoWill(TakePhotosOfFailures),
            new SerenityBDDReporter(),
            new ConsoleReporter() // removing this line gets rid of error
        ]
    },
    cucumberOpts: {
        require: ['./features/**/*.ts'],
        format: ['pretty'], 
        compiler: 'ts:ts-node/register'
    },
};
```

**Comment by testifyqa** [comment]
```
[18:40:03] E/launcher - Error: TypeError: Cannot read property 'println' of undefined
    at MatchesObjectsWithCommonPrototype.transformation (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/console-reporter/src/stage/crew/console-reporter/ConsoleReporter.ts:193:30)
    at MatchesObjectsWithCommonPrototype.MatcherRule.execute (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/tiny-types/src/pattern-matching/rules/MatcherRule.ts:13:21)
    at ObjectMatcher.PatternMatcher.else (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/tiny-types/src/pattern-matching/PatternMatcher.ts:17:71)
    at ConsoleReporter.notifyOf (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/console-reporter/src/stage/crew/console-reporter/ConsoleReporter.ts:325:18)
    at /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/core/src/stage/StageManager.ts:33:59
    at Array.forEach (<anonymous>)
    at StageManager.notifyOf (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/core/src/stage/StageManager.ts:33:26)
    at Stage.announce (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/core/src/stage/Stage.ts:111:22)
    at Serenity.announce (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/core/src/Serenity.ts:30:20)
    at /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/cucumber/src/notifier/Notifier.ts:138:47
    at Array.forEach (<anonymous>)
    at Notifier.emit (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/cucumber/src/notifier/Notifier.ts:138:16)
    at Notifier.scenarioStarts (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/cucumber/src/notifier/Notifier.ts:55:18)
    at EventEmitter.<anonymous> (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/cucumber/src/listeners/CucumberEventProtocolAdapter.ts:110:26)
    at EventEmitter.emit (events.js:215:7)
[18:40:03] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details.
➜  serenity-js-framework git:(develop/help-jan-find-bugs) ✗ 
```

**Comment by testifyqa** [comment]
maybe related to #358 work? not sure sorry

**Comment by testifyqa** [comment]
hmm having just read https://github.com/nbarrett/serenity-js/blob/2.0-migration-guide/documentation/website/src/handbook/tutorials/serenity-2-migration-guide.md, this may not be an issue if you just specify the colour theme to use with the console reporter
