### ISSUE TITLE
Initializers are not allowed in ambient contexts. (1039) within Question

### ISSUE THREAD

**Issue by nbarrett** [jan-molak/serenity-js#42]
I think I've got everything configured for my mocha-powered serenity project but I'm having a compilation error as follows:

```
[18:13:10] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
client/spec/screenplay/questions/walksProgrammeQuestions.ts (5,48): Initializers are not allowed in ambient contexts. (1039)
    at getOutput (/Users/nick/dev/git-personal/ekwg/node_modules/ts-node/src/index.ts:302:15)
    at /Users/nick/dev/git-personal/ekwg/node_modules/ts-node/src/index.ts:333:16
    at Object.compile (/Users/nick/dev/git-personal/ekwg/node_modules/ts-node/src/index.ts:492:17)
    at Module.m._compile (/Users/nick/dev/git-personal/ekwg/node_modules/ts-node/src/index.ts:385:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/nick/dev/git-personal/ekwg/node_modules/ts-node/src/index.ts:388:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
````

In my Question class I'm getting this tell-tale sign:

![image](https://cloud.githubusercontent.com/assets/626941/26366704/f990c4b8-3fe3-11e7-9ae2-a51bec2c528f.png)

Information [on the web](https://www.google.co.uk/search?q=Initializers+are+not+allowed+in+ambient+contexts.+(1039)&oq=Initializers+are+not+allowed+in+ambient+contexts.+(1039)&aqs=chrome..69i57.635j0j9&sourceid=chrome&ie=UTF-8#q=error+ts1039:+initializers+are+not+allowed+in+ambient+contexts.) suggests I'm using a pre-2.1 version of typescript, but this isn't the case according to my package.json:

```
    "ts-node": "^3.0.4",
    "tslint": "4.2.0",
    "typescript": "2.3.3",
```

So @jan-molak --- heeeelp please!

**Comment by nbarrett** [comment]
Ah.. actually I ditched the `declare` from my class and everything got better..... I must have copied the source from a type definition file arrgh!! 😊

**Comment by jan-molak** [comment]
Yup, `export class` is all you need:

```typescript
export class WalksProgrammeQuestions {
  // ...
}
```
