### ISSUE TITLE
Test results can return a false positive even when an assertion fails

### ISSUE THREAD

**Issue by testifyqa** [jan-molak/serenity-js#424]
I have a protractor test that runs and passes fine, but when I changed the assertion to make it fail, the console gave me the following 

```
Subscribe to newsletter: Subscribing to the newsletter with an invalid email address

  Given that Ned decides to use Zagat to stay updated with recommended restaurants
    ✓ Ned navigates to '/national' (1s 295ms)
  When he tries to subscribe to the newsletter with his email address of 'nedstark'
    Ned subscribes to the newsletter with nedstark
      ✓ Ned enters 'nedstark' into the initial email field (443ms)
      ✓ Ned clicks on the submit email address button (82ms)
  Then he is prevented by validation that reads "Please include an '@' in the email address. 'nedstark' is missing an '@'."

✓ Execution successful (1s 838ms)
================================================================================
Execution Summary

Subscribe to newsletter: 2 successful, 2 total (5s 117ms)

Total time: 5s 117ms
Scenarios:  2
================================================================================
  ✗ Ned ensures that the value of the 'validationMessage' attribute of the initial email field does equal 'foobar' (116ms)

    Difference (+ expected, - actual):

    - "Please include an '@' in the email address. 'nedstark' is missing an '@'."
    + 'foobar'

(node:38323) UnhandledPromiseRejectionWarning: AssertionError: Expected the value of the 'validationMessage' attribute of the initial email field to equal 'foobar'
    at Ensure.asAssertionError (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/assertions/src/Ensure.ts:56:16)
    at Ensure.errorForOutcome (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/assertions/src/Ensure.ts:52:21)
    at MatchesObjectsWithCommonPrototype.transformation (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/assertions/src/Ensure.ts:33:36)
    at MatchesObjectsWithCommonPrototype.MatcherRule.execute (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/tiny-types/src/pattern-matching/rules/MatcherRule.ts:13:21)
    at ObjectMatcher.PatternMatcher.else (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/tiny-types/src/pattern-matching/PatternMatcher.ts:17:71)
    at /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/@serenity-js/assertions/src/Ensure.ts:36:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:38323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12:27:12] I/launcher - 0 instance(s) of WebDriver still running
[12:27:12] I/launcher - chrome #01 passed
➜  serenity-js-framework git:(master) ✗ 
```

My step file...
```
import { When, Then } from "cucumber";
import { actorInTheSpotlight, See } from "@serenity-js/core";
import { SubscribeToNewsletter } from "../../spec/screenplay/tasks/SubscribeToNewsletter";
import { Ensure, includes, equals } from "@serenity-js/assertions";
import { Website, isVisible, Attribute } from "@serenity-js/protractor";
import { ZagatNewsletterSubscriptionWidget } from "../../spec/screenplay/ui/ZagatNewsletterSubscriptionWidget";
import { EmailValidationMessage } from "../../spec/screenplay/EmailValidationMessage";

When('he/she tries to subscribe to the newsletter with his/her email address of {string}', (emailAddress: string) => 
    actorInTheSpotlight().attemptsTo(SubscribeToNewsletter.with(emailAddress))
);

Then('he/she is asked to also provide his/her zip code to accompany {string}', (expectedEmailAddress: string) => 
    actorInTheSpotlight().attemptsTo(
        Ensure.that(Website.url(), includes('/newsletters?email='+expectedEmailAddress)), // check url we land on contains expected email address
        Ensure.that(ZagatNewsletterSubscriptionWidget.zipCodeField, isVisible()) // check that zip code field is displayed
    )
);

Then('he/she is prevented by validation that reads {string}', (expectedValidationMessage: string) => {
    actorInTheSpotlight().attemptsTo(
        Ensure.that(EmailValidationMessage(), equals('foobar')) // check that returned validation message is same as expected one
    )
});
```

EmailValidationMessage() const:
```
import { Attribute } from "@serenity-js/protractor";
import { ZagatNewsletterSubscriptionWidget } from "./ui/ZagatNewsletterSubscriptionWidget";

export const EmailValidationMessage = () => Attribute.of(ZagatNewsletterSubscriptionWidget.initialEmailField).called('validationMessage');
```

Please let me know if you need more details. 

Although the console shows the difference between expected and actual in the assertion as well as some stack trace, I didn't expect it to say "successful" at the top

**Comment by jan-molak** [comment]
Is it the little curly bracket in the `Then` step?

```
Then('he/she is prevented by validation that reads {string}', (expectedValidationMessage: string) => {
    actorInTheSpotlight().attemptsTo(    // <- this promise is never returned
        Ensure.that(EmailValidationMessage(), equals('foobar')) // check that returned validation message is same as expected one
    )
});
```

**Comment by testifyqa** [comment]
Doh! That's it, my bad, long day today ha. Thanks, have pushed change and updated blog so will close this off :)

**Comment by testifyqa** [comment]
i think its because the pending step comes with the curly brackets then i forgot to remove them when defining the step 🤦‍♂

**Comment by jan-molak** [comment]
No worries, @testifyqa, happens to the best of us!
