### ISSUE TITLE
Setup Errors

### ISSUE THREAD

**Issue by cladroma** [jan-molak/serenity-js#46]
I am following the instructions to set up Serenity-js ([here](https://github.com/jan-molak/serenity-js-getting-started/tree/2-reports)) , but ran into errors on "npm test" on one of the "updates" it tried to do:

C:\Users\cladroma\serenity-js-getting-started>npm test

> serenity-js-getting-started@1.0.0 test C:\Users\cladroma\serenity-js-getting-started
> npm run protractor

> serenity-js-getting-started@1.0.0 preprotractor C:\Users\cladroma\serenity-js-getting-started
> npm run webdriver:update -- --standalone

> serenity-js-getting-started@1.0.0 webdriver:update C:\Users\cladroma\serenity-js-getting-started
> npm run webdriver-manager update "--standalone"

> serenity-js-getting-started@1.0.0 webdriver-manager C:\Users\cladroma\serenity-js-getting-started
> ./node_modules/protractor/bin/webdriver-manager "update"

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serenity-js-getting-started@1.0.0 webdriver-manager: `./node_modules/protractor/bin/webdriver-manager "update"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serenity-js-getting-started@1.0.0 webdriver-manager script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cladroma\AppData\Roaming\npm-cache\_logs\2017-05-25T15_01_58_803Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serenity-js-getting-started@1.0.0 webdriver:update: `npm run webdriver-manager update "--standalone"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serenity-js-getting-started@1.0.0 webdriver:update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cladroma\AppData\Roaming\npm-cache\_logs\2017-05-25T15_01_58_936Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serenity-js-getting-started@1.0.0 preprotractor: `npm run webdriver:update -- --standalone`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serenity-js-getting-started@1.0.0 preprotractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cladroma\AppData\Roaming\npm-cache\_logs\2017-05-25T15_01_59_087Z-debug.log
npm ERR! Test failed.  See above for more details.

C:\Users\cladroma\serenity-js-getting-started>

C:\Users\cladroma\serenity-js-getting-started>

The logs displayed:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\cladroma\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@4.6.1
3 info using node@v6.10.3
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle serenity-js-getting-started@1.0.0~preprotractor: serenity-js-getting-started@1.0.0
6 verbose lifecycle serenity-js-getting-started@1.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle serenity-js-getting-started@1.0.0~preprotractor: PATH: C:\Users\cladroma\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\cladroma\serenity-js-getting-started\node_modules\.bin;C:\Users\cladroma\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\cladroma\serenity-js-getting-started\node_modules\.bin;C:\Windows\System32\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Java\jre1.8.0_71\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs;C:\Program Files\apache-maven-3.5.0\bin;C:\Users\cladroma\AppData\Local\GitHubDesktop;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jre1.8.0_131\bin;C:\Program Files\nodejs\;C:\Users\cladroma\.dnx\bin;C:\Users\cladroma\AppData\Roaming\npm
8 verbose lifecycle serenity-js-getting-started@1.0.0~preprotractor: CWD: C:\Users\cladroma\serenity-js-getting-started
9 silly lifecycle serenity-js-getting-started@1.0.0~preprotractor: Args: [ '/d /s /c', 'npm run webdriver:update -- --standalone' ]
10 silly lifecycle serenity-js-getting-started@1.0.0~preprotractor: Returned: code: 1  signal: null
11 info lifecycle serenity-js-getting-started@1.0.0~preprotractor: Failed to exec preprotractor script
12 verbose stack Error: serenity-js-getting-started@1.0.0 preprotractor: `npm run webdriver:update -- --standalone`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\cladroma\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\cladroma\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:886:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid serenity-js-getting-started@1.0.0
14 verbose cwd C:\Users\cladroma\serenity-js-getting-started
15 verbose Windows_NT 10.0.10586
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cladroma\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
17 verbose node v6.10.3
18 verbose npm  v4.6.1
19 error code ELIFECYCLE
20 error errno 1
21 error serenity-js-getting-started@1.0.0 preprotractor: `npm run webdriver:update -- --standalone`
21 error Exit status 1
22 error Failed at the serenity-js-getting-started@1.0.0 preprotractor script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by cladroma** [comment]
there is a  newer installation that i will now try to follow
