### ISSUE TITLE
Fail:  node_modules/serenity-js/lib/serenity-protractor/plugin Plugin Tests

### ISSUE THREAD

**Issue by oscarbuho888** [jan-molak/serenity-js#48]
When i try to run "npm test" The following error is displayed:

```
1 scenario (1 passed)
3 steps (3 passed)
0m04.651s
[SerenityProtractorPlugin] An error occurred during teardown TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:539:5)
    at D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity\stage\json_reporter.ts:226:38
    at process._tickCallback (internal/process/next_tick.js:109:7)
[16:56:28] I/plugins -           Fail:  node_modules/serenity-js/lib/serenity-protractor/plugin Plugin Tests
[16:56:28] E/plugins -          Failure during teardown: Path must be a string. Received undefined
[16:56:28] E/plugins -          TypeError: Path must be a string. Received undefined
                    at assertPath (path.js:7:11)
                    at Object.relative (path.js:539:5)
                    at D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity\stage\json_reporter.ts:226:38
                    at process._tickCallback (internal/process/next_tick.js:109:7)
[16:56:29] I/local - Shutting down selenium standalone server.
[16:56:29] I/launcher - 0 instance(s) of WebDriver still running
[16:56:29] I/launcher - chrome #01 failed 1 test(s)
[16:56:29] I/launcher - overall: 1 failed spec(s)
[16:56:29] E/launcher - Process exited with error code 1
```

**Comment by jan-molak** [comment]
Thanks, looks like the tutorial still uses an old (`0.x`) version of the `serenity-js` module; let me update that.

**Comment by nbarrett** [comment]
Hi @jan-molak - actually when I look at the console output from my test, i get lots of this:
```
[chrome #01-0] (node:49912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): TypeError: Path must be a string. Received undefined
```

The test still seems to run okay. I originally created my project about a year ago, so I'm wondering whether part of it is out of date... is there an obvious area I should look to fix this please?

**Comment by jan-molak** [comment]
Hey @nbarrett - hard to tell without a stacktrace; OP is referring to `json_reporter.ts:226:38` which is long gone ...

**Comment by nbarrett** [comment]
Ah, sorry @jan-molak - I've added `debug: true,` and now the test returns the the following config:
```
(node:50777) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 26)
[21:43:05] E/launcher - Error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1153:7)
    at FileSystem.prepareDirectory (/Users/nick/dev/git-personal/ekwg/node_modules/@serenity-js/core/src/io/file_system.ts:27:33)
    at /Users/nick/dev/git-personal/ekwg/node_modules/@serenity-js/core/src/io/file_system.ts:15:40
    at process._tickCallback (internal/process/next_tick.js:109:7)
[21:43:05] E/launcher - Process exited with error code 100
```

my dependencies are a follows:
```
    "@types/chai": "3.4.34",
    "@types/chai-as-promised": "0.0.29",
    "@types/mocha": "2.2.39",
    "@types/node": "6.0.73",
    "chai": "3.5.0",
    "chai-as-promised": "6.0.0",
    "chai-smoothie": "^0.2.1",
    "mocha": "^3.2.0",
    "protractor": "^5.1.2",
    "rimraf": "^2.5.4",
    "serenity-cli": "^0.2.4",
    "serenity-js": "1.10.2",
    "ts-node": "4.1.0",
    "tslint": "4.4.2",
    "tslint-microsoft-contrib": "4.0.0",
    "typescript": "2.3.4",
```
