### ISSUE TITLE
Error: TypeError: serenity.scenarioLifeCycleNotifier is not a function

### ISSUE THREAD

**Issue by oscarbuho888** [jan-molak/serenity-js#51]
Hi @jan-molak , After updating the version of serenity-js (1.5.0) in "package.json": 

![image](https://cloud.githubusercontent.com/assets/13580205/26559587/2fbafcfc-4476-11e7-981a-d6fe6b720bd6.png)

And then remove "plugins" from "protractor.conf.js":

![image](https://cloud.githubusercontent.com/assets/13580205/26559669/a3309700-4476-11e7-9cdc-9713ec284a00.png)

When I try to run I get the following error:

```
[13:40:39] E/launcher - Error: TypeError: serenity.scenarioLifeCycleNotifier is not a function
    at Object.module.exports (D:\SerenityJs\serenity-js-getting-started\features\cucumber.hooks.ts:6:36)
    at D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:65:25
    at Array.forEach (native)
    at Object.wrapper (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:62:15)
    at Object.initializer (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:24:41)
    at Object.Library (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\support_code\library.js:133:25)
    at Object.getSupportCodeLibrary (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\cli\configuration.js:128:32)
    at Object.getSupportCodeLibrary (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\runtime.js:44:46)
    at Object.start (D:\SerenityJs\serenity-js-getting-started\node_modules\cucumber\lib\cucumber\runtime.js:12:37)
[13:40:39] E/launcher - Process exited with error code 100

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\SerenityJs\\serenity-js-getting-started\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v6.10.3
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! serenity-js-getting-started@1.0.0 protractor: `node ./node_modules/protractor/bin/protractor ./protractor.conf.js --silent`
npm ERR! Exit status 100
```

You have done the other more updated examples and they work for me, but I want this to work for me, since I need to know how to get the "index.html". And this is the only example that shows how to do it.

Thank you very much¡

**Comment by jan-molak** [comment]
Hey @oscarbuho888, Serenity/JS registers Cucumber hooks automatically now, so [those lines](https://github.com/jan-molak/serenity-js-getting-started/blob/2-reports/features/cucumber.hooks.ts#L6-L8) are no longer needed and you can remove them from your `D:\SerenityJs\serenity-js-getting-started\features\cucumber.hooks.ts`.

Hope this helps!
Jan

**Comment by oscarbuho888** [comment]
Thank you @jan-molak . I have already advanced with the implementation but now I get the following error:

Failures:

1) Scenario: Adding an item to a list with other items - features\add_new_items.feature:7
   Step: Given that James has a todo list containing Buy some cookies, Walk the dog - features\add_new_items.feature:9
   Step Definition: node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:47
   Message:
     TypeError: Cannot read property 'theActorCalled' of undefined
         at .<anonymous> (D:\SerenityJs\serenity-js-getting-started\features\step_definitions\todo_user.steps.ts:26:26)
         at D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:45
         at TaskQueue.execute_ (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:2860:25)
         at D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:109:7)
     From: Task: <anonymous>
         at stepWrapper (D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:18)
         at stepWrapper (D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:104:32)
         at arity2 (eval at <anonymous> (D:\SerenityJs\serenity-js-getting-started\node_modules\util-arity\arity.js:22:24), <anonymous>:3:45)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)


![image](https://cloud.githubusercontent.com/assets/13580205/26566794/8f54117c-44bb-11e7-8d76-dcd569caa63b.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566815/b0ffe710-44bb-11e7-98f2-39253c84eea5.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566835/cf5962f4-44bb-11e7-9895-efc758315a9a.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566848/e4f27704-44bb-11e7-957b-cc64b2af80d6.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566860/09160326-44bc-11e7-8a3b-117d1076fe2c.png)

**Comment by oscarbuho888** [comment]
I already found the solution. I was changing function arrow (=>) by function expression.

I do not have much experience with TypeScript =)

**Comment by jan-molak** [comment]
No worries, I'm glad that you manage to work it out. By the way, you might want to check out @basarat's excellent ["TypeScript Deep Dive"](https://basarat.gitbooks.io/typescript/content/), which is one of my favourite resources on TypeScript.

Hope that helps!
