### ISSUE TITLE
TypeError: Cannot read property 'theActorCalled' of undefined

### ISSUE THREAD

**Issue by oscarbuho888** [jan-molak/serenity-js#52]
I have already advanced with the implementation but now I get the following error:

Failures:

1) Scenario: Adding an item to a list with other items - features\add_new_items.feature:7
   Step: Given that James has a todo list containing Buy some cookies, Walk the dog - features\add_new_items.feature:9
   Step Definition: node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:47
   Message:
     **TypeError: Cannot read property 'theActorCalled' of undefined**
         at .<anonymous> (D:\SerenityJs\serenity-js-getting-started\features\step_definitions\todo_user.steps.ts:26:26)
         at D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:45
         at TaskQueue.execute_ (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:2860:25)
         at D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:109:7)
     From: Task: <anonymous>
         at stepWrapper (D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:18)
         at stepWrapper (D:\SerenityJs\serenity-js-getting-started\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:104:32)
         at arity2 (eval at <anonymous> (D:\SerenityJs\serenity-js-getting-started\node_modules\util-arity\arity.js:22:24), <anonymous>:3:45)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)

![image](https://cloud.githubusercontent.com/assets/13580205/26566794/8f54117c-44bb-11e7-8d76-dcd569caa63b.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566815/b0ffe710-44bb-11e7-98f2-39253c84eea5.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566835/cf5962f4-44bb-11e7-9895-efc758315a9a.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566848/e4f27704-44bb-11e7-957b-cc64b2af80d6.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566860/09160326-44bc-11e7-8a3b-117d1076fe2c.png)

![image](https://cloud.githubusercontent.com/assets/13580205/26566890/55b7b922-44bc-11e7-9619-8bd9781affb6.png)

**Comment by oscarbuho888** [comment]
I already found the solution. I was changing function arrow (=>) by function expression.

I do not have much experience with TypeScript =)
