### ISSUE TITLE
Configuration: integrator-browserstack-tunnel

### ISSUE THREAD

**Issue by oscarbuho888** [jan-molak/serenity-js#54]
Hi, i tried configurate BrowserStack Tunel with:

```
npm install --save integrator-browserstack-tunnel
```

But I can't make it work. My configuration is as follows:

```
configurations: {
browserstack: {
plugins: [
new integratorBrowserstackTunnel('userKey')
],
common: {
hub: 'http://hub.browserstack.com/wd/hub',
capabilities: {
'browserstack.user' : process.env.BROWSERSTACK_USERNAME || 'userName',
'browserstack.key' : process.env.BROWSERSTACK_ACCESS_KEY || 'userKey',
'build': 'protractor-browserstack',
'name': 'local_test',
'browserName': 'chrome',
'browserstack.local': true,
'browserstack.debug': 'true'
}
},
}
}
```

And the Error shown is:

```
/launcher - Running 1 instances of WebDriver
[21:46:44] I/hosted - Using the selenium server at http://hub.browserstack.com/wd/hub
[21:46:45] E/launcher - Authorization required
[21:46:45] E/launcher - WebDriverError: Authorization required
at WebDriverError (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\error.js:27:5)
at parseHttpResponse (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\http.js:521:11)
at doSend.then.response (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\http.js:440:13)
at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
at Function.createSession (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
at Function.createSession (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\chrome.js:709:29)
at createDriver (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\index.js:167:33)
at Builder.build (D:\SerenityJs\serenity-js-getting-started\node_modules\selenium-webdriver\index.js:623:16)
at Hosted.getNewDriver (D:\SerenityJs\serenity-js-getting-started\node_modules\protractor\lib\driverProviders\driverProvider.ts:60:29)
at Runner.createBrowser (D:\SerenityJs\serenity-js-getting-started\node_modules\protractor\lib\runner.ts:225:39)
at q.then.then (D:\SerenityJs\serenity-js-getting-started\node_modules\protractor\lib\runner.ts:391:27)
at _fulfilled (D:\SerenityJs\serenity-js-getting-started\node_modules\q\q.js:834:54)
at self.promiseDispatch.done (D:\SerenityJs\serenity-js-getting-started\node_modules\q\q.js:863:30)
at Promise.promise.promiseDispatch (D:\SerenityJs\serenity-js-getting-started\node_modules\q\q.js:796:13)
[21:46:45] E/launcher - Process exited with error code 199
```

If someone already configured this, please tell me how to do it

Thank you¡

**Comment by jan-molak** [comment]
Hey @oscarbuho888,

It seems to me that the [integrator-browserstack-tunnel](https://www.npmjs.com/package/integrator-browserstack-tunnel) is an [integrator](https://github.com/tgvashworth/integrator) plugin and is not designed to work with Protractor?

Have a look at the [BrowserStack documentation](https://www.browserstack.com/automate/protractor) to learn more about configuring BrowserStack-related capabilities.

Hope this helps!
Jan
