### ISSUE TITLE
Another: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by dpkano** [jan-molak/serenity-js#55]
Hi,
    When I use chai-string I get this:
```
RangeError: Maximum call stack size exceeded
         at Object (native)
         at baseGetTag (BLABLA\node_modules\lodash\lodash.js:3078:51)
         at baseClone (BLABLA\node_modules\lodash\lodash.js:2663:19)
         at BLABLA\node_modules\lodash\lodash.js:2702:34
         at arrayEach (BLABLA\node_modules\lodash\lodash.js:537:11)
         at baseClone (BLABLA\node_modules\lodash\lodash.js:2696:7)
         at cloneSet (BLABLA\node_modules\lodash\lodash.js:4591:28)
         at initCloneByTag (BLABLA\node_modules\lodash\lodash.js:6254:18)
         at baseClone (BLABLA\node_modules\lodash\lodash.js:2680:20)
         at BLABLA\node_modules\lodash\lodash.js:2702:34
         at arrayEach (BLABLA\node_modules\lodash\lodash.js:537:11)
         at baseClone (BLABLA\node_modules\lodash\lodash.js:2696:7)
         at BLABLA\node_modules\lodash\lodash.js:2702:34
         at arrayEach (BLABLA\node_modules\lodash\lodash.js:537:11)
         at baseClone (BLABLA\node_modules\lodash\lodash.js:2696:7)
         at BLABLA\node_modules\lodash\lodash.js:2702:34
     From: Task: <anonymous>
         at World.stepWrapper (BLABLA\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:18)
         at World.stepWrapper (BLABLA\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:104:32)
         at World.arity1 (eval at <anonymous> (BLABLA\node_modules\util-arity\arity.js:22:24), <anonymous>:3:41)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)
```

And the Step is doing this:

```
       this.Then(/^Bla bla$/, () => {
        return this.stage.theActorInTheSpotlight().attemptsTo(
            ...
            See.if(Tab.MyText("HEY!"),
                (txt) => expect(txt).to.eventually.deep.be.equalIgnoreCase("HELLO!"))
        );
       });

```

If I change equalIgnoreCase to equal, it works (the test fails, but it works...)
Any idea? Thanks.

**Comment by jan-molak** [comment]
Hmm, could this be a chai-related issue?

In the below sample:

```javascript
expect(txt).to.eventually.deep.be.equalIgnoreCase("HELLO!"))
```

string comparison doesn't need `deep` or `be`... Would that work instead?

```javascript
expect(txt).to.eventually.equalIgnoreCase("HELLO!")
```

**Comment by dpkano** [comment]
Yes. I just checked that. Thanks for the quick reply!! :)

**Comment by jan-molak** [comment]
Excellent, glad it worked! :)
