### ISSUE TITLE
UnexpectedAlertOpenError causes test to terminate and produce no output

### ISSUE THREAD

**Issue by nbarrett** [jan-molak/serenity-js#65]
In my attempts to write some tasks that handle and accept alerts, I discovered that when webdriver -> protractor -> serenity-js encounters the exception: `UnexpectedAlertOpenError` then the test terminates and produces no json -> html output at all. See [#branch for issue-65](https://github.com/nbarrett/serenity-js-issues/tree/issue-65) for a reproducible test case.

**Comment by nbarrett** [comment]
Hey @jan-molak when running `npm test` on the above branch the following exception is thrown:
```
[00:52:38] E/launcher - Error: UnexpectedAlertOpenError: unexpected alert open: {Alert text : Only selected walks in the published state will be unpublished.

Are you sure you want to unpublish the selected walks?}
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6 milliseconds: null
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Nicks-MBP', ip: '2a02:c7f:ca16:e000:f484:4cd8:881c:f73c', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262), userDataDir=/var/folders/ny/3mg4vv816758l5fjfqjwgqjr0000gn/T/.org.chromium.Chromium.DE4LIT}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: d74456d511b0deef53ababa5476b278f
    at Object.checkLegacyResponse (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/selenium-webdriver/lib/error.js:512:13)
    at parseHttpResponse (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.takeScreenshot()
    at thenableWebDriverProxy.schedule (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at thenableWebDriverProxy.takeScreenshot (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/selenium-webdriver/lib/webdriver.js:1092:17)
    at run (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/protractor/lib/browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as takeScreenshot] (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/protractor/lib/browser.ts:74:12)
    at /Users/nick/dev/git-personal/serenity-js-issues/node_modules/serenity-js/src/serenity-protractor/screenplay/abilities/browse_the_web.ts:42:41
    at /Users/nick/dev/git-personal/serenity-js-issues/node_modules/@serenity-js/core/src/recording/async.ts:4:8
    at Object.defer (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/@serenity-js/core/src/recording/async.ts:3:12)
    at BrowseTheWeb.takeScreenshot (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/serenity-js/src/serenity-protractor/screenplay/abilities/browse_the_web.ts:42:16)
    at Photographer.photographWorkOf (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/serenity-js/src/serenity-protractor/stage/photographer.ts:136:36)
    at Photographer.photograph (/Users/nick/dev/git-personal/serenity-js-issues/node_modules/serenity-js/src/serenity-protractor/stage/photographer.ts:114:38)
[00:52:38] E/launcher - Process exited with error code 100

```

**Comment by nbarrett** [comment]
Note that in my attempt to circumnavigate the Unpexpected alert I tried catching the exception as follows, but to no avail:

```
  performAs(actor: PerformsTasks): PromiseLike<void> {
        return actor.attemptsTo(
            Click.on(RamblersTargets.unPublishSelected)).catch(e => {
            console.log('exception thrown', e);
            return actor.attemptsTo(
                Click.on(RamblersTargets.unPublishSelected),
                WaitForAlert.toBePresent(),
                Alert.accept());
        });

    }
```

**Comment by jan-molak** [comment]
Ha, so that's an interesting one. I think you're right, the Photographer assumes that every task is related to an interaction with the browser window. An alert, however, doesn't allow for a screenshot to be taken.

I think the error handling should be added [here](https://github.com/jan-molak/serenity-js/blob/6e374193ec5bc7e015246b0a8c83ee429c2bd8d3/packages/serenity-js/src/serenity-protractor/stage/photographer.ts#L119). If we can't take the screenshot because we're focused on an alert dialog, we ignore the problem the same way we handle WebDriver's invalid session perhaps?

J

**Comment by nbarrett** [comment]
Hi @jan-molak - thanks for response... are you wanting me to have a go at a PR for this error handling?

**Comment by jan-molak** [comment]
That would be lovely :-) Thanks!

**Comment by nbarrett** [comment]
HI @jan-molak - I've made the necessary changes now - hope I got everything! 🙏

**Comment by jan-molak** [comment]
PR merged; closing.

Thanks for your contribution, @nbarrett !

J
