### ISSUE TITLE
Support for typescript. 

### ISSUE THREAD

**Issue by mrj04** [jan-molak/serenity-js#80]
Error: TypeError: Cannot call a class as a function
    at exports.default (/Users/xyz/git/login/node_modules/babel-runtime/helpers/classCallCheck.js:7:11)
    at Object.Cli (/Users/xyz/git/login/node_modules/cucumber/lib/cli/index.js:64:34)
    at /Users/xyz/git/login/node_modules/serenity-js/src/serenity-cucumber/cucumber_test_framework.ts:24:22
    at Promise (<anonymous>)
    at CucumberTestFramework.run (/Users/xyz/git/login/node_modules/serenity-js/src/serenity-cucumber/cucumber_test_framework.ts:21:16)
    at /Users/xyz/git/login/node_modules/serenity-js/src/serenity-protractor/framework/serenity_protractor_framework.ts:52:35
    at _fulfilled (/Users/xyz/git/login/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/xyz/git/login/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/xyz/git/login/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/xyz/git/login/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/xyz/git/login/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/xyz/git/login/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jan-molak** [comment]
Hi there, @mrj04! It's quite difficult for me to figure out how to help you based on the stack trace alone. Could you please give me a bit more context and explain what you're trying to do?

**Comment by jbprat** [comment]
@mrj04 I had the same error while I was configurating, it turns out I had installed CucumberJS 2+ when SerenityJS only supports Cucumber 1+. You can check your version of CucumberJS.

**Comment by mrj04** [comment]
thanks @jbprat
