### ISSUE TITLE
How to use iframe switch

### ISSUE THREAD

**Issue by DeChrish** [jan-molak/serenity-js#82]
How to switch between iframe in Task.
`browser.switchTo().frame(0);` 

Sample Task
```
@step('{0} adds a Component Group called #itemName')          // Gives the Task a more descriptive name
    performAs(actor: PerformsTasks): PromiseLike<void> {
        return actor.attemptsTo(
        Wait.upTo(Long_Enough).until(InsertComponentGroup.Component_Parsys, Is.visible()),
        Click.on(InsertComponentGroup.Component_Parsys),
        Click.on(InsertComponentGroup.Insert_Component),
        Click.on(InsertComponentGroup.Close_Component_Group)
        );
    }
```

Stack Trace
```
WebDriverError:` unknown error: Element <div data-type="Editable" data-path="/content/demo-test/en/national/global-shared/author-test/button-home/jcr:content/bodypar/*" tabindex="0" draggable="false" data-text="Drag components here" title="Drag components here" class="cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder" style="top: 500px; left: 0px; width: 1050px; height: 46px;"></div> is not clickable at point (525, 567). Other element would receive the click: <div data-type="Editable" data-path="/content/demo-test/en/national/global-shared/author-test/button-home/jcr:content/bodypar/button_1768048491" tabindex="0" draggable="true" class="cq-Overlay cq-Overlay--component cq-draggable cq-droptarget" style="top: 0px; left: 0px; width: 1050px; height: 546px;"></div>
       (Session info: chrome=60.0.3112.90)
       (Driver info: chromedriver=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
     Command duration or timeout: 46 milliseconds
     Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
     System info: host: 'MACLTUS49392', ip: '10.0.0.127', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_144'
     Driver info: org.openqa.selenium.chrome.ChromeDriver
     Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f), userDataDir=/var/folders/z2/hppjr3sx52v0n592kypb85500000gs/T/.org.chromium.Chromium.6THC57}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=60.0.3112.90, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
     Session ID: e4c4d6d2f155727e4c26c0ae8b9450b2
         at Object.checkLegacyResponse (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/error.js:505:15)
         at parseHttpResponse (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/http.js:509:13)
         at doSend.then.response (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/http.js:440:13)
         at process._tickCallback (internal/process/next_tick.js:109:7)
     From: Task: WebElement.click()
         at thenableWebDriverProxy.schedule (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
         at WebElement.schedule_ (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
         at WebElement.click (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/webdriver.js:2002:17)
         at actionFn (/Users/DeChrish/Documents/demo/author-serenity/node_modules/protractor/lib/element.ts:94:34)
         at Array.map (native)
         at actionResults.getWebElements.then (/Users/DeChrish/Documents/demo/author-serenity/node_modules/protractor/lib/element.ts:484:67)
         at ManagedPromise.invokeCallback_ (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/promise.js:1366:14)
         at TaskQueue.execute_ (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/promise.js:2970:14)
         at TaskQueue.executeNext_ (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/promise.js:2953:27)
         at asyncRun (/Users/DeChrish/Documents/demo/author-serenity/node_modules/selenium-webdriver/lib/promise.js:2813:27)Error
         at ElementArrayFinder.applyAction_ (/Users/DeChrish/Documents/demo/author-serenity/node_modules/protractor/lib/element.ts:482:23)
         at ElementArrayFinder.(anonymous function).args [as click] (/Users/DeChrish/Documents/demo/author-serenity/node_modules/protractor/lib/element.ts:96:21)
         at ElementFinder.(anonymous function).args [as click] (/Users/DeChrish/Documents/demo/author-serenity/node_modules/protractor/lib/element.ts:873:14)
         at Click.performAs (/Users/DeChrish/Documents/demo/author-serenity/node_modules/serenity-js/src/serenity-protractor/screenplay/interactions/click.ts:13:59)
         at /Users/DeChrish/Documents/demo/author-serenity/node_modules/@serenity-js/core/src/screenplay/actor.ts:112:43
         at process._tickCallback (internal/process/next_tick.js:109:7)
     From: Task: <anonymous>
         at World.stepWrapper (/Users/DeChrish/Documents/demo/author-serenity/node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:72:18)
         at World.stepWrapper (/Users/DeChrish/Documents/demo/author-serenity/node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:104:32)
         at World.arity0 (eval at module.exports (/Users/DeChrish/Documents/demo/author-serenity/node_modules/util-arity/arity.js:22:24), <anonymous>:3:39)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by nbarrett** [comment]
Hey @DeChrish - from your stack trace, this appears to be the [widely reported](https://stackoverflow.com/questions/11908249/debugging-element-is-not-clickable-at-point-error) 'element is not clickable at point', not anything to do with iframe switching. FYI, #65 contains an attempt to switch between iframes but awaits @jan-molak's expertise!

**Comment by DeChrish** [comment]
@nbarrett  thanks. will check it again.
