### ISSUE TITLE
TypeError: Cannot read property 'fileName' of undefined

### ISSUE THREAD

**Issue by DeChrish** [jan-molak/serenity-js#84]
`node : v8.3.0`
`npm : 5.3.0`

Stack Trace:
```
TypeError: Cannot read property 'fileName' of undefined
         at to_location (/Users/DeChrish/Documents/pet/author-serenity/node_modules/serenity-js/node_modules/@serenity-js/core/src/screenplay/actor.ts:152:22)
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:188:7)
     From: Task: <anonymous>
         at World.stepWrapper (/Users/DeChrish/Documents/pet/author-serenity/node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:72:18)
         at World.stepWrapper (/Users/DeChrish/Documents/pet/author-serenity/node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:104:32)
         at World.arity1 (eval at module.exports (/Users/DeChrish/Documents/pet/author-serenity/node_modules/serenity-js/node_modules/util-arity/arity.js:22:24), <anonymous>:3:41)
         at _combinedTickCallback (internal/process/next_tick.js:131:7)
         at process._tickCallback (internal/process/next_tick.js:180:9)

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)
```

**Comment by jan-molak** [comment]
Hi there! Could you please give me a bit more context so that I can try to reproduce the issue you're facing?

**Comment by DeChrish** [comment]
@jan-molak  added test repo : https://github.com/DeChrish/author-serenity

**Comment by DeChrish** [comment]
@jan-molak any help?

**Comment by jan-molak** [comment]
So this is what I'm seeing:

```
λ ~/Downloads/author-serenity/ [master] npm test

> author-serenity@1.0.0 test /Users/janek/Downloads/author-serenity
> npm run protractor --silent

[21:43:19] I/file_manager - creating folder /Users/janek/Downloads/author-serenity/node_modules/protractor/node_modules/webdriver-manager/selenium
[21:43:22] I/update - geckodriver: unzipping geckodriver-v0.18.0.tar.gz
[21:43:22] I/update - geckodriver: setting permissions to 0755 for /Users/janek/Downloads/author-serenity/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.18.0
[21:43:25] I/update - chromedriver: unzipping chromedriver_2.31.zip
[21:43:25] I/update - chromedriver: setting permissions to 0755 for /Users/janek/Downloads/author-serenity/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.31
(node:10392) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[21:43:32] I/launcher - Running 1 instances of WebDriver
[21:43:32] I/local - Starting selenium standalone server...
[21:43:33] I/local - Selenium standalone server started at http://192.168.1.107:56331/wd/hub
Feature: Add button component to the button page

  Scenario: Adding an button component to a button page with other components
  ✖ Given that Richard has access to author instance to author the button component
  ? When he adds Button component to test page
  ? Then his bbutton page should contain Button component

Failures:

1) Scenario: Adding an button component to a button page with other components - features/add_new_component.feature:3
   Step: Given that Richard has access to author instance to author the button component - features/add_new_component.feature:5
   Step Definition: node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:47
   Message:
     NoSuchElementError: No element found using locator: By(css selector, *[id="username"])
         at elementArrayFinder.getWebElements.then (/Users/janek/Downloads/author-serenity/node_modules/protractor/lib/element.ts:851:17)
         at ManagedPromise.invokeCallback_ (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/promise.js:1366:14)
         at TaskQueue.execute_ (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/promise.js:2970:14)
         at TaskQueue.executeNext_ (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/promise.js:2953:27)
         at asyncRun (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/promise.js:2813:27)
         at /Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:109:7)Error
         at ElementArrayFinder.applyAction_ (/Users/janek/Downloads/author-serenity/node_modules/protractor/lib/element.ts:482:23)
         at ElementArrayFinder.(anonymous function).args [as sendKeys] (/Users/janek/Downloads/author-serenity/node_modules/protractor/lib/element.ts:96:21)
         at ElementFinder.(anonymous function).args [as sendKeys] (/Users/janek/Downloads/author-serenity/node_modules/protractor/lib/element.ts:873:14)
         at EnterValue.performAs (/Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-protractor/screenplay/interactions/enter.ts:41:59)
         at /Users/janek/Downloads/author-serenity/node_modules/@serenity-js/core/src/screenplay/actor.ts:112:43
         at process._tickCallback (internal/process/next_tick.js:109:7)
     From: Task: <anonymous>
         at World.stepWrapper (/Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:72:18)
         at World.stepWrapper (/Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:104:32)
         at World.arity1 (eval at module.exports (/Users/janek/Downloads/author-serenity/node_modules/util-arity/arity.js:22:24), <anonymous>:3:41)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)

Warnings:

1) Scenario: Adding an button component to a button page with other components - features/add_new_component.feature:3
   Step: When he adds Button component to test page - features/add_new_component.feature:6
   Message:
     Undefined. Implement with the following snippet:

       this.When(/^he adds Button component to test page$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

2) Scenario: Adding an button component to a button page with other components - features/add_new_component.feature:3
   Step: Then his bbutton page should contain Button component - features/add_new_component.feature:7
   Message:
     Undefined. Implement with the following snippet:

       this.Then(/^his bbutton page should contain Button component$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

1 scenario (1 failed)
3 steps (1 failed, 2 undefined)
0m01.197s
[21:43:41] E/launcher - Error: WebDriverError: java.net.SocketException: Connection reset by peer (connect failed)
    at Object.checkLegacyResponse (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.takeScreenshot()
    at thenableWebDriverProxy.schedule (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at thenableWebDriverProxy.takeScreenshot (/Users/janek/Downloads/author-serenity/node_modules/selenium-webdriver/lib/webdriver.js:1092:17)
    at run (/Users/janek/Downloads/author-serenity/node_modules/protractor/lib/browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as takeScreenshot] (/Users/janek/Downloads/author-serenity/node_modules/protractor/lib/browser.ts:74:12)
    at /Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-protractor/screenplay/abilities/browse_the_web.ts:42:41
    at /Users/janek/Downloads/author-serenity/node_modules/@serenity-js/core/src/recording/async.ts:4:8
    at Object.defer (/Users/janek/Downloads/author-serenity/node_modules/@serenity-js/core/src/recording/async.ts:3:12)
    at BrowseTheWeb.takeScreenshot (/Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-protractor/screenplay/abilities/browse_the_web.ts:42:16)
    at Photographer.photographWorkOf (/Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-protractor/stage/photographer.ts:136:36)
    at Photographer.photograph (/Users/janek/Downloads/author-serenity/node_modules/serenity-js/src/serenity-protractor/stage/photographer.ts:114:38)
[21:43:41] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details.
```

What are the exact steps you'd like me to take in order to reproduce the issue?

By the way: are you sure that all the dependencies, such as protractor in particular, are local (so no dependencies installed with `-g`)?

**Comment by DeChrish** [comment]
@jan-molak my bad. it is working; may be messed up with my shell on that day.

**Comment by jan-molak** [comment]
Not a problem at all, happy to help! 👍

**Comment by sabau** [comment]
Hi @jan-molak, I'm facing the same problem. (I'm using Windows 7 64bit)
I had node v6.11.3 and my project worked fine.
I had to upgrade to node v8.6.0, then v8.7.0 and with both versions I incurred in the same error in 

`@serenity-js\core\src\screenplay\actor.ts line 152,22` frame was undefined

My particular case was for the following sequence of actions, I was able to Wait, Click and navigate, but not use Enter:

```javascript
@step('{0} login as  "#username"')
public performAs(actor: PerformsTasks): PromiseLike<void> {
    return actor.attemptsTo(
        Wait.until(LoginPage.targets.loginForm, Is.present()),
        Click.on(LoginPage.targets.usernameField),
        Enter.theValue(this.username).into(LoginPage.targets.usernameField), <--BREAKS HERE
        Click.on(LoginPage.targets.passwordField),
        Enter.theValue(this.password).into(LoginPage.targets.passwordField),
        Click.on(LoginPage.targets.submitButton),
        Wait.upTo(new Duration(this.timeout)).until(BasePage.targets.spinner, Is.invisible())
    );
}
```

I solved by downgrading to node v6.11.4 and everything is working fine again, but trying version 8 again caused another time the same problem.

**Comment by metrophos** [comment]
I have same behavior like @sabau. My system is Linux

**Comment by jan-molak** [comment]
Thanks @sabau, my aim with Serenity/JS is to always support the latest Long Term Support version of Node, so 6.11.x at the moment. As soon as Node 8 becomes an LTS I'll look into supporting it properly. In the meantime, if anyone would like to look into enabling Node 8 support, I'd be more than happy to assist with a pull request?

**Comment by sabau** [comment]
I'll try to look more in depth on this as soon as I have some spare time :)

I've seen some tickets that seems related to node 8. If you agree, I'll open an issue about node 8 support to reference them all
