### ISSUE TITLE
Error: TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by AnandGanesh-Reflektion** [jan-molak/serenity-js#91]
Hi @jan-molak, I have followed the instructions provided at
https://github.com/jan-molak/serenity-js/blob/master/docs/from-scripts-to-serenity-getting-started-writing-what-you-would-like-to-read.md
and 
https://github.com/jan-molak/serenity-js/blob/master/docs/from-scripts-to-serenity-reporting-making-the-tests-speak-for-themselves.md

But I ended up seeing the following error.

```
[23:12:17] W/runner - Ignoring unknown extra flags: silent. This will be an error in future versions, please use --disableChecks flag to disable the  Protractor CLI flag checks. 
[23:12:17] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
features/cucumber.hooks.ts (8,58): Property 'controlFlow' does not exist on type 'ExtendedWebDriver'. (2339)
    at getOutput (/Users/reflektion/anand/dev-cloud/serenity-js/serenity-js-getting-started/node_modules/ts-node/src/index.ts:253:17)
    at /Users/reflektion/anand/dev-cloud/serenity-js/serenity-js-getting-started/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (/Users/reflektion/anand/dev-cloud/serenity-js/serenity-js-getting-started/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (/Users/reflektion/anand/dev-cloud/serenity-js/serenity-js-getting-started/node_modules/ts-node/src/index.ts:299:46)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/reflektion/anand/dev-cloud/serenity-js/serenity-js-getting-started/node_modules/ts-node/src/index.ts:302:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[23:12:17] E/launcher - Process exited with error code 100

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! serenity-js-getting-started@1.0.0 protractor: `./node_modules/protractor/bin/protractor ./protractor.conf.js --silent`
npm ERR! Exit status 100
```

I use Webstorm as my IDE. 
I am new to typescript.  How can I compile all ts files in the project?
![screen shot 2017-08-29 at 11 24 33 pm](https://user-images.githubusercontent.com/29747350/29835971-4bb1b598-8d11-11e7-9dab-3c42de2cef70.jpg)

Thanks,
Anand

**Comment by jan-molak** [comment]
Hi Anand,

Could you please share the `features/cucumber.hooks.ts` file mentioned in your stack trace?

Thanks,
Jan

**Comment by jan-molak** [comment]
Closing due to inactivity. Please let me know if you're still experiencing this issue and we can re-open the ticket.
